package dev.dreamwalker.bloodbornedw.link;

import dev.dreamwalker.bloodbornedw.architecture.*;
import dev.dreamwalker.bloodbornerp.object.*;
import net.fabricmc.fabric.api.gametest.v1.FabricGameTest;
import net.minecraft.test.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.nbt.NbtCompound;
import java.util.*;

/** Technical server semantics only; ordinary mouse/GUI packet proof is separate. */
public final class MechanismRulesGameTests implements FabricGameTest {
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void allUsesPersistentFlagsAndClosesOnlyOnConditionTransition(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),b=object(c,"lever_2",3),door=object(c,"door_1",9);var r=MechanismRules.create(p,"ALL durable");add(c,p,r,a,true);add(c,p,r,b,true);add(c,p,r,door,false);c.assertTrue(MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE),"configure ALL");
        MechanismRules.pulse(a);c.assertTrue(!door.isOpen()&&MechanismRules.flag(p.getServer(),a.getUuid()),"one source is persistent active but1/2 does not open");MechanismRules.pulse(b);c.assertTrue(door.isOpen(),"all2/2 opens actual target");for(int i=0;i<80;i++){a.tick();b.tick();}c.assertTrue(door.isOpen()&&MechanismRules.flag(p.getServer(),a.getUuid()),"temporary lever animation does not clear source flag");MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"ALL false transition closes rather than toggles blindly");cleanup(p,a,b,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void creationOrderSurvivesTypedRoundtripAndLastActualActionWins(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9);MechanismRules.Rule open=MechanismRules.create(p,"first OPEN"),close=MechanismRules.create(p,"last CLOSE");for(var r:List.of(open,close)){add(c,p,r,a,true);add(c,p,r,door,false);}MechanismRules.configure(p,open.id,open.name,MechanismRules.Condition.ANY,MechanismRules.Effect.OPEN);MechanismRules.configure(p,close.id,close.name,MechanismRules.Condition.ANY,MechanismRules.Effect.CLOSE);MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"last rule closes actual opened target");NbtCompound n=MechanismRules.get(p.getServer()).writeNbt(new NbtCompound());NbtCompound round=MechanismRules.fromNbt(n).writeNbt(new NbtCompound());c.assertTrue(round.equals(n),"typed flags, order, and members survive save decode");cleanup(p,a,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void removingRequiredAllSourceMarksIncompleteAndDoesNotOpen(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),b=object(c,"lever_2",3),door=object(c,"door_1",9);var r=MechanismRules.create(p,"required sources");add(c,p,r,a,true);add(c,p,r,b,true);add(c,p,r,door,false);MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE);MechanismRules.pulse(a);b.removeByBuilder();c.assertTrue(r.incomplete&&!r.satisfied&&!door.isOpen(),"deletion does not silently fulfil reducedALL");MechanismRules.pulse(a);MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"incomplete rule cannot act until composition repaired");cleanup(p,a,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void resetSharedAllFlagsDoesNotGenerateAnyPulse(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),allDoor=object(c,"door_1",9),anyDoor=object(c,"door_2",14);MechanismRules.Rule all=MechanismRules.create(p,"all"),any=MechanismRules.create(p,"any");add(c,p,all,a,true);add(c,p,all,allDoor,false);add(c,p,any,a,true);add(c,p,any,anyDoor,false);MechanismRules.configure(p,all.id,all.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE);MechanismRules.pulse(a);c.assertTrue(allDoor.isOpen()&&anyDoor.isOpen(),"successful event delivers bothconditions");c.assertTrue(MechanismRules.reset(p,all.id),"explicit reset accepted");c.assertTrue(!allDoor.isOpen()&&anyDoor.isOpen()&&!MechanismRules.flag(p.getServer(),a.getUuid()),"reset updatesALL butdoesnot pulseANY");cleanup(p,a,allDoor,anyDoor);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void mixedPersistentAndPulseTargetsRunOnceAtAllTrueOnly(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9),gate=object(c,"wood_gate",19);var r=MechanismRules.create(p,"mixed");add(c,p,r,a,true);add(c,p,r,door,false);add(c,p,r,gate,false);c.assertTrue(MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE),"mixedsupported");MechanismRules.pulse(a);c.assertTrue(door.isOpen()&&gate.woodGatePulseActive()&&!gate.isOpen(),"actual door open andsingle gateclip nofakeOPEN");for(int i=0;i<32;i++)gate.tick();MechanismRules.retry(p.getServer(),256);c.assertTrue(!gate.woodGatePulseActive(),"ticks/retry don't repeat satisfiedALLpulse");MechanismRules.pulse(a);c.assertTrue(!door.isOpen()&&!gate.woodGatePulseActive(),"ALLfalse closesdoor without gatepulse");cleanup(p,a,door,gate);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void pendingSafeCloseWaitsAndQueueAndInitiatorPersist(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9);door.setOpen(true);var r=MechanismRules.create(p,"safeclose");add(c,p,r,a,true);add(c,p,r,door,false);MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ANY,MechanismRules.Effect.CLOSE);var living=net.minecraft.entity.EntityType.ARMOR_STAND.create(c.getWorld());living.setPosition(door.getPos());c.getWorld().spawnEntity(living);MechanismLinks.noteInitiator(a,p);MechanismRules.pulse(a);var ref=MechanismLinks.TargetRef.rp(door);c.assertTrue(door.isOpen()&&MechanismRules.pending(p.getServer(),ref),"real occupant keeps actualstateopen queued");NbtCompound n=MechanismRules.get(p.getServer()).writeNbt(new NbtCompound());c.assertTrue(n.getList("Queue",10).stream().map(v->(NbtCompound)v).anyMatch(v->v.getCompound("Target").getUuid("Instance").equals(door.getUuid())&&v.getCompound("Initiator").getUuid("UUID").equals(p.getUuid())),"queued exacttarget and initiator typed persisted");living.discard();MechanismRules.retry(p.getServer(),256);c.assertTrue(!door.isOpen()&&!MechanismRules.pending(p.getServer(),ref),"pendingclose commitsonly when safe");cleanup(p,a,door);c.complete();}
    private static ServerPlayerEntity player(TestContext c){var p=c.createMockCreativeServerPlayerInWorld();p.getAbilities().creativeMode=true;p.getAbilities().allowModifyWorld=true;return p;}
    private static RpObjectEntity object(TestContext c,String asset,int x){var rp=ObjectRegistry.TYPES.get(asset).create(c.getWorld());BlockPos root=c.getAbsolutePos(new BlockPos(x,2,1));rp.refreshPositionAndAngles(root.getX()+.5,root.getY(),root.getZ()+.5,0,0);c.getWorld().spawnEntity(rp);return rp;}
    private static void add(TestContext c,ServerPlayerEntity p,MechanismRules.Rule r,RpObjectEntity entity,boolean source){c.assertTrue(MechanismRules.add(p,r.id,MechanismLinks.TargetRef.rp(entity),source),"actual instance accepted:"+entity.assetId());}
    private static void cleanup(ServerPlayerEntity p,RpObjectEntity... entities){for(var e:entities)e.removeByBuilder();p.discard();}
}
