package dev.dreamwalker.bloodbornedw.link;

import dev.dreamwalker.bloodbornedw.architecture.*;
import dev.dreamwalker.bloodbornerp.object.*;
import net.fabricmc.fabric.api.gametest.v1.FabricGameTest;
import net.minecraft.test.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.nbt.NbtCompound;
import java.util.*;

/** Technical server semantics only; ordinary mouse/GUI packet proof is separate. */
public final class MechanismRulesGameTests implements FabricGameTest {
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void allUsesPersistentFlagsAndClosesOnlyOnConditionTransition(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),b=object(c,"lever_2",3),door=object(c,"door_1",9);var r=MechanismRules.create(p,"ALL durable");add(c,p,r,a,true);add(c,p,r,b,true);add(c,p,r,door,false);c.assertTrue(MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE),"configure ALL");
        MechanismRules.pulse(a);c.assertTrue(!door.isOpen()&&MechanismRules.flag(p.getServer(),a.getUuid()),"one source is persistent active but1/2 does not open");MechanismRules.pulse(b);c.assertTrue(door.isOpen(),"all2/2 opens actual target");for(int i=0;i<80;i++){a.tick();b.tick();}c.assertTrue(door.isOpen()&&MechanismRules.flag(p.getServer(),a.getUuid()),"temporary lever animation does not clear source flag");MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"ALL false transition closes rather than toggles blindly");cleanup(p,a,b,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void creationOrderSurvivesTypedRoundtripAndLastActualActionWins(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9);MechanismRules.Rule open=MechanismRules.create(p,"first OPEN"),close=MechanismRules.create(p,"last CLOSE");for(var r:List.of(open,close)){add(c,p,r,a,true);add(c,p,r,door,false);}MechanismRules.configure(p,open.id,open.name,MechanismRules.Condition.ANY,MechanismRules.Effect.OPEN);MechanismRules.configure(p,close.id,close.name,MechanismRules.Condition.ANY,MechanismRules.Effect.CLOSE);MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"last rule closes actual opened target");NbtCompound n=MechanismRules.get(p.getServer()).writeNbt(new NbtCompound());NbtCompound round=MechanismRules.fromNbt(n).writeNbt(new NbtCompound());c.assertTrue(round.equals(n),"typed flags, order, and members survive save decode");cleanup(p,a,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void removingRequiredAllSourceMarksIncompleteAndDoesNotOpen(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),b=object(c,"lever_2",3),door=object(c,"door_1",9);var r=MechanismRules.create(p,"required sources");add(c,p,r,a,true);add(c,p,r,b,true);add(c,p,r,door,false);MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE);MechanismRules.pulse(a);b.removeByBuilder();c.assertTrue(r.incomplete&&!r.satisfied&&!door.isOpen(),"deletion does not silently fulfil reducedALL");MechanismRules.pulse(a);MechanismRules.pulse(a);c.assertTrue(!door.isOpen(),"incomplete rule cannot act until composition repaired");cleanup(p,a,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void resetSharedAllFlagsDoesNotGenerateAnyPulse(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),allDoor=object(c,"door_1",9),anyDoor=object(c,"door_2",14);MechanismRules.Rule all=MechanismRules.create(p,"all"),any=MechanismRules.create(p,"any");add(c,p,all,a,true);add(c,p,all,allDoor,false);add(c,p,any,a,true);add(c,p,any,anyDoor,false);MechanismRules.configure(p,all.id,all.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE);MechanismRules.pulse(a);c.assertTrue(allDoor.isOpen()&&anyDoor.isOpen(),"successful event delivers bothconditions");c.assertTrue(MechanismRules.reset(p,all.id),"explicit reset accepted");c.assertTrue(!allDoor.isOpen()&&anyDoor.isOpen()&&!MechanismRules.flag(p.getServer(),a.getUuid()),"reset updatesALL butdoesnot pulseANY");cleanup(p,a,allDoor,anyDoor);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void mixedPersistentAndPulseTargetsRunOnceAtAllTrueOnly(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9),gate=object(c,"wood_gate",19);var r=MechanismRules.create(p,"mixed");add(c,p,r,a,true);add(c,p,r,door,false);add(c,p,r,gate,false);c.assertTrue(MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE),"mixedsupported");MechanismRules.pulse(a);c.assertTrue(door.isOpen()&&gate.woodGatePulseActive()&&!gate.isOpen(),"actual door open andsingle gateclip nofakeOPEN");for(int i=0;i<32;i++)gate.tick();MechanismRules.retry(p.getServer(),256);c.assertTrue(!gate.woodGatePulseActive(),"ticks/retry don't repeat satisfiedALLpulse");MechanismRules.pulse(a);c.assertTrue(!door.isOpen()&&!gate.woodGatePulseActive(),"ALLfalse closesdoor without gatepulse");cleanup(p,a,door,gate);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_rules")
    public void pendingSafeCloseWaitsAndQueueAndInitiatorPersist(TestContext c){var p=player(c);RpObjectEntity a=object(c,"lever_1",1),door=object(c,"door_1",9);door.setOpen(true);var r=MechanismRules.create(p,"safeclose");add(c,p,r,a,true);add(c,p,r,door,false);MechanismRules.configure(p,r.id,r.name,MechanismRules.Condition.ANY,MechanismRules.Effect.CLOSE);var living=net.minecraft.entity.EntityType.ARMOR_STAND.create(c.getWorld());living.setPosition(door.getPos());c.getWorld().spawnEntity(living);MechanismLinks.noteInitiator(a,p);MechanismRules.pulse(a);var ref=MechanismLinks.TargetRef.rp(door);c.assertTrue(door.isOpen()&&MechanismRules.pending(p.getServer(),ref),"real occupant keeps actualstateopen queued");NbtCompound n=MechanismRules.get(p.getServer()).writeNbt(new NbtCompound());c.assertTrue(n.getList("Queue",10).stream().map(v->(NbtCompound)v).anyMatch(v->v.getCompound("Target").getUuid("Instance").equals(door.getUuid())&&v.getCompound("Initiator").getUuid("UUID").equals(p.getUuid())),"queued exacttarget and initiator typed persisted");living.discard();MechanismRules.retry(p.getServer(),256);c.assertTrue(!door.isOpen()&&!MechanismRules.pending(p.getServer(),ref),"pendingclose commitsonly when safe");cleanup(p,a,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void atomicDraftSaveRejectsEmptyAndStaleFormsWithoutPartialRules(TestContext c){var p=player(c);var lever=object(c,"lever_1",1);var door=object(c,"door_1",9);var sr=MechanismLinks.TargetRef.rp(lever);var tr=MechanismLinks.TargetRef.rp(door);int before=MechanismRules.list(p.getServer()).size();
        c.assertTrue(!MechanismRules.createValid(p,"empty",MechanismRules.Condition.ANY,MechanismRules.Effect.TOGGLE,List.of(sr),List.of()).success()&&MechanismRules.list(p.getServer()).size()==before,"incomplete draft creates no persistent record");
        var saved=MechanismRules.createValid(p,"valid",MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE,List.of(sr),List.of(tr));c.assertTrue(saved.success(),"complete composition commits atomically");String version=MechanismRules.fingerprint(p.getServer(),saved.rule());MechanismRules.pulse(lever);c.assertTrue(version.equals(MechanismRules.fingerprint(p.getServer(),saved.rule())),"gameplay flags do not overwrite or invalidate editable configuration");
        c.assertTrue(MechanismRules.saveValid(p,saved.rule(),version,"second player",MechanismRules.Condition.ALL,MechanismRules.Effect.OPEN,List.of(sr),List.of(tr)).success(),"current version commits");
        c.assertTrue(!MechanismRules.saveValid(p,saved.rule(),version,"stale player",MechanismRules.Condition.ANY,MechanismRules.Effect.CLOSE,List.of(sr),List.of(tr)).success()&&MechanismRules.rule(p.getServer(),saved.rule()).name.equals("second player"),"stale form refuses and keeps the other edit");cleanup(p,lever,door);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void simpleThreeTargetsAreIdempotentAndPreserveOriginalLeverDelay(TestContext c){var p=player(c);var a=object(c,"lever_1",1);var b=object(c,"lever_2",3);var d1=object(c,"door_1",9);var d2=object(c,"door_2",15);var sr=MechanismLinks.TargetRef.rp(a);
        var root=c.getAbsolutePos(new BlockPos(24,2,12));c.getWorld().setBlockState(root.down(),net.minecraft.block.Blocks.STONE.getDefaultState());var block=dev.dreamwalker.bloodbornedw.composite.CompositeArchitecture.kindBlock("prototype_double_door");var state=block.getDefaultState();for(var cell:block.spec.footprint(state,0).keySet())c.getWorld().getChunk(root.add(cell.x(),cell.y(),cell.z()));
        c.assertTrue(dev.dreamwalker.bloodbornedw.composite.CompositeRuntime.place(c.getWorld(),root,state,UUID.randomUUID(),null).outcome()==dev.dreamwalker.bloodbornedw.runtime.TransactionCore.Outcome.COMMITTED,"real architectural door fixture");var owner=((dev.dreamwalker.bloodbornedw.composite.CompositeBlockEntity)c.getWorld().getBlockEntity(root)).resident();var architecture=CompositeMechanismBridge.reference(c.getWorld(),owner);
        try{for(var target:List.of(MechanismLinks.TargetRef.rp(d1),MechanismLinks.TargetRef.rp(d2),architecture))c.assertTrue(MechanismRules.simpleConnect(p,sr,target).success(),"default simple pair accepts target");int count=MechanismRules.list(p.getServer()).size();var again=MechanismRules.simpleConnect(p,sr,MechanismLinks.TargetRef.rp(d1));c.assertTrue(again.success()&&!again.changed()&&MechanismRules.list(p.getServer()).size()==count,"repeat does not add a rule or target");p.setPosition(a.getX()+1,a.getY(),a.getZ());a.interact(p,net.minecraft.util.Hand.MAIN_HAND);for(int i=0;i<69;i++)a.tick();c.assertTrue(!d1.isOpen()&&!d2.isOpen()&&!c.getWorld().getBlockState(root).get(dev.dreamwalker.bloodbornedw.composite.CompositeRootBlock.OPEN),"three targets wait the original 69 ticks");a.tick();c.assertTrue(d1.isOpen()&&d2.isOpen()&&c.getWorld().getBlockState(root).get(dev.dreamwalker.bloodbornedw.composite.CompositeRootBlock.OPEN),"70th tick operates all three actual targets");c.assertTrue(MechanismRules.simpleConnect(p,MechanismLinks.TargetRef.rp(b),MechanismLinks.TargetRef.rp(d1)).success(),"another lever shares the actual target");MechanismRules.pulse(b);c.assertTrue(!d1.isOpen()&&d2.isOpen(),"second lever changes only its target");c.assertTrue(MechanismRules.simpleUnlink(p,sr,MechanismLinks.TargetRef.rp(d1)).success()&&MechanismLinks.targets(a).size()==2,"unlink removes selected pair only");c.complete();}finally{dev.dreamwalker.bloodbornedw.composite.CompositeRuntime.remove(c.getWorld(),owner,null,false);cleanup(p,a,b,d1,d2);}}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void groupPairRefusesImplicitRestructureAndConflictingSimpleRule(TestContext c){var p=player(c);var a=object(c,"lever_1",1);var b=object(c,"lever_2",3);var door=object(c,"door_1",9);var ar=MechanismLinks.TargetRef.rp(a);var br=MechanismLinks.TargetRef.rp(b);var tr=MechanismLinks.TargetRef.rp(door);
        var result=MechanismRules.createValid(p,"two sources",MechanismRules.Condition.ALL,MechanismRules.Effect.OPEN,List.of(ar,br),List.of(tr));var rule=MechanismRules.rule(p.getServer(),result.rule());c.assertTrue(result.success(),"complete group saved");c.assertTrue(!MechanismRules.simpleUnlink(p,ar,tr).success()&&rule.sources.size()==2&&rule.targets.size()==1,"single-pair unlink cannot silently erase other group participants");var other=object(c,"lever_1",5);c.assertTrue(!MechanismRules.simpleConnect(p,MechanismLinks.TargetRef.rp(other),tr).success()&&rule.sources.size()==2,"contradictory default TOGGLE rule is explained/refused and old group retained");cleanup(p,a,b,door,other);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void deletingImportedMemberCannotResurrectFromOldEntityLinks(TestContext c){var p=player(c);var a=object(c,"lever_1",1);var d1=object(c,"door_1",9);var d2=object(c,"door_2",15);c.assertTrue(a.addLink(d1)&&a.addLink(d2),"legacy source has two bindings");var old=a.writeNbt(new NbtCompound());var legacy=MechanismRules.get(p.getServer()).writeNbt(new NbtCompound());legacy.putInt("Schema",1);for(var tag:legacy.getList("Rules",10))((NbtCompound)tag).remove("Simple");var migrated=MechanismRules.fromNbt(legacy).writeNbt(new NbtCompound());c.assertTrue(migrated.getInt("Schema")==2&&migrated.getList("Rules",10).stream().map(v->(NbtCompound)v).anyMatch(v->v.getUuid("Id").equals(a.getUuid())&&v.getBoolean("Simple")),"schema1 UUID links infer simple marker under schema2 without new UUIDs");var r=MechanismRules.rule(p.getServer(),a.getUuid());c.assertTrue(r!=null&&MechanismRules.removeMember(p,r.id,MechanismLinks.TargetRef.rp(d1).key(),false),"only first member deleted");a.remove(net.minecraft.entity.Entity.RemovalReason.UNLOADED_TO_CHUNK);var restored=ObjectRegistry.TYPES.get("lever_1").create(c.getWorld());restored.readNbt(old);c.assertTrue(c.getWorld().spawnEntity(restored),"exact source UUID reloads stale pre-edit entity payload");MechanismLinks.loaded(restored);c.assertTrue(!restored.links().contains(d1.getUuid())&&MechanismLinks.targets(restored).stream().noneMatch(t->t.instance().equals(d1.getUuid()))&&MechanismLinks.targets(restored).size()==1,"authoritative saved graph rejects resurrection and preserves second pair");MechanismRules.pulse(restored);c.assertTrue(!d1.isOpen()&&d2.isOpen(),"only retained member receives event");cleanup(p,restored,d1,d2);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void deletingLegacyRulePreservesOtherCoveringRuleAndPhysicalObjects(TestContext c){var p=player(c);var a=object(c,"lever_1",1);var d1=object(c,"door_1",9);var d2=object(c,"door_2",15);c.assertTrue(a.addLink(d1)&&a.addLink(d2),"legacy pair fixture");var retained=MechanismRules.create(p,"existing second rule");add(c,p,retained,a,true);add(c,p,retained,d1,false);c.assertTrue(MechanismRules.delete(p,a.getUuid()),"delete only named legacy rule");MechanismLinks.loaded(a);c.assertTrue(MechanismRules.rule(p.getServer(),retained.id)!=null&&retained.targets.size()==1&&!a.isRemoved()&&!d1.isRemoved()&&!d2.isRemoved(),"other existing rule and physical objects retained");c.assertTrue(a.links().contains(d1.getUuid())&&!a.links().contains(d2.getUuid()),"only uncovered old entity binding removed");MechanismRules.pulse(a);c.assertTrue(d1.isOpen()&&!d2.isOpen(),"retained other rule still operates its target once");cleanup(p,a,d1,d2);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="tool_fix_rules")
    public void savedRuleCanRenameWithUnloadedUnchangedMembersButRejectsNewUnavailableTargets(TestContext c){var p=player(c);var a=object(c,"lever_1",1);var door=object(c,"door_1",9);var sr=MechanismLinks.TargetRef.rp(a);var tr=MechanismLinks.TargetRef.rp(door);var saved=MechanismRules.createValid(p,"loaded",MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE,List.of(sr),List.of(tr));c.assertTrue(saved.success(),"loaded valid rule created");a.remove(net.minecraft.entity.Entity.RemovalReason.UNLOADED_TO_CHUNK);door.remove(net.minecraft.entity.Entity.RemovalReason.UNLOADED_TO_CHUNK);c.assertTrue(c.getWorld().getEntity(a.getUuid())==null&&MechanismLinks.inspect(p.getServer(),tr).availability()==MechanismLinks.Availability.UNLOADED,"both exact existing members are unloaded");
        String version=MechanismRules.fingerprint(p.getServer(),saved.rule());var renamed=MechanismRules.saveValid(p,saved.rule(),version,"renamed unloaded",MechanismRules.Condition.ALL,MechanismRules.Effect.TOGGLE,List.of(sr),List.of(tr));c.assertTrue(renamed.success()&&c.getWorld().getEntity(a.getUuid())==null&&c.getWorld().getEntity(door.getUuid())==null,"metadata save preserves unloaded references without bringing entities back");var r=MechanismRules.rule(p.getServer(),saved.rule());var unavailable=new MechanismLinks.TargetRef(MechanismLinks.Kind.RP,tr.dimension(),UUID.randomUUID(),new BlockPos(30000,70,30000).asLong(),"door_1");c.assertTrue(!MechanismRules.addValid(p,r.id,unavailable,false,MechanismRules.fingerprint(p.getServer(),r.id)).success()&&r.targets.size()==1,"new unloaded target is refused without changing prior saved composition");c.assertTrue(!c.getWorld().isChunkLoaded(BlockPos.fromLong(unavailable.root())),"new unavailable target lookup does not load its far chunk");MechanismRules.delete(p,r.id);MechanismRules.removed(p.getServer(),sr);MechanismRules.removed(p.getServer(),tr);p.discard();c.complete();}
    private static ServerPlayerEntity player(TestContext c){var p=c.createMockCreativeServerPlayerInWorld();p.getAbilities().creativeMode=true;p.getAbilities().allowModifyWorld=true;return p;}
    private static RpObjectEntity object(TestContext c,String asset,int x){var rp=ObjectRegistry.TYPES.get(asset).create(c.getWorld());BlockPos root=c.getAbsolutePos(new BlockPos(x,2,1));rp.refreshPositionAndAngles(root.getX()+.5,root.getY(),root.getZ()+.5,0,0);c.getWorld().spawnEntity(rp);return rp;}
    private static void add(TestContext c,ServerPlayerEntity p,MechanismRules.Rule r,RpObjectEntity entity,boolean source){c.assertTrue(MechanismRules.add(p,r.id,MechanismLinks.TargetRef.rp(entity),source),"actual instance accepted:"+entity.assetId());}
    private static void cleanup(ServerPlayerEntity p,RpObjectEntity... entities){for(var e:entities)e.removeByBuilder();p.discard();}
}
