package dev.dreamwalker.bloodbornedw.link;
import dev.dreamwalker.bloodbornerp.object.*;
import net.fabricmc.fabric.api.gametest.v1.FabricGameTest;
import net.minecraft.test.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.Hand;
import java.util.*;

/** Real state/command semantics; GUI permission and clicks require the separate client probe. */
public final class ObjectPolicyGameTests implements FabricGameTest {
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_policies")
    public void instanceManualRestrictionPreservesLeverControlAndOtherInstance(TestContext c){var p=c.createMockCreativeServerPlayerInWorld();RpObjectEntity door=object(c,"door_1",9),other=object(c,"door_1",16),lever=object(c,"lever_1",1);var ref=MechanismLinks.TargetRef.rp(door);c.assertTrue(ObjectPolicies.setManual(p,ref,true),"specific instance policy accepted");p.setPosition(door.getX(),door.getY(),door.getZ()+1);door.interact(p,Hand.MAIN_HAND);c.assertTrue(!door.isOpen()&&!door.isLocked(),"hands blocked without genericLocked");c.assertTrue(!ObjectPolicies.leversOnly(p.getServer(),MechanismLinks.TargetRef.rp(other)),"same type differentUUID staysmanual");lever.addLink(door);MechanismLinks.pulse(lever);c.assertTrue(door.isOpen(),"lever bypasses manual-onlyrestriction");ObjectPolicies.setManual(p,ref,false);settle(door);p.setPosition(door.getX()+6,door.getY(),door.getZ()+6);door.interact(p,Hand.MAIN_HAND);c.assertTrue(!door.isOpen(),"restoring manualmode allows actualclose");cleanup(p,door,other,lever);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_policies")
    public void creativeCannotAssignConsoleCommandsAndPulseHasNoOpenHook(TestContext c){var p=c.createMockCreativeServerPlayerInWorld();RpObjectEntity door=object(c,"door_1",9),gate=object(c,"wood_gate",18);c.assertTrue(!p.hasPermissionLevel(4)&&!ObjectPolicies.setCommands(p,MechanismLinks.TargetRef.rp(door),true,List.of("say forbidden")),"Creative alone cannot assign consolecommands");p.getServer().getPlayerManager().getOpList().add(new net.minecraft.server.OperatorEntry(p.getGameProfile(),4,false));try{c.assertTrue(p.hasPermissionLevel(4),"isolated test operator really haslevel4");c.assertTrue(!ObjectPolicies.setCommands(p,MechanismLinks.TargetRef.rp(gate),true,List.of("say unsupported")),"pulseonly gate has no inventedafterOPEN");}finally{p.getServer().getPlayerManager().removeFromOperators(p.getGameProfile());}cleanup(p,door,gate);c.complete();}
    @GameTest(templateName=FabricGameTest.EMPTY_STRUCTURE,tickLimit=100,batchId="v10_policies")
    public void hooksRunOnlyAfterActualSuccessAndOnceDespiteIdempotentRetry(TestContext c){var p=c.createMockCreativeServerPlayerInWorld();var door=object(c,"door_1",9);var ref=MechanismLinks.TargetRef.rp(door);var server=p.getServer();String objective="dw"+UUID.randomUUID().toString().replace("-","").substring(0,10);var source=server.getCommandSource().withLevel(4).withSilent();server.getCommandManager().executeWithPrefix(source,"scoreboard objectives add "+objective+" dummy");server.getPlayerManager().getOpList().add(new net.minecraft.server.OperatorEntry(p.getGameProfile(),4,false));try{
        c.assertTrue(ObjectPolicies.setCommands(p,ref,true,List.of("scoreboard players add opened "+objective+" 1"))&&ObjectPolicies.setCommands(p,ref,false,List.of("scoreboard players add closed "+objective+" 1")),"actual level4 policy editor accepts orderedcommands");c.assertTrue(door.setOpen(true)&&door.setOpen(true),"one real open plus idempotent repeat accepted");c.assertTrue(door.animationBusy()&&!door.setOpen(false),"busy open clip rejects an immediate opposite state without a close hook");settle(door);c.assertTrue(server.getCommandManager().executeWithPrefix(source,"scoreboard players get opened "+objective)==1,"one real openhook; no idempotent/tickduplicate");
        var living=net.minecraft.entity.EntityType.ARMOR_STAND.create(c.getWorld());living.setPosition(door.getPos());c.getWorld().spawnEntity(living);c.assertTrue(!door.setOpen(false),"living-safeclose rejectedbefore actualtransition");c.assertTrue(server.getCommandManager().executeWithPrefix(source,"scoreboard players get closed "+objective)==0,"no closehook onfailedrequest");living.discard();c.assertTrue(door.setOpen(false),"actual close now succeeds");c.assertTrue(server.getCommandManager().executeWithPrefix(source,"scoreboard players get closed "+objective)==1,"one realclosehook");
    }finally{server.getPlayerManager().removeFromOperators(p.getGameProfile());server.getCommandManager().executeWithPrefix(source,"scoreboard objectives remove "+objective);}cleanup(p,door);c.complete();}
    private static void settle(RpObjectEntity object){var clip=object.asset().clip(object.isOpen()?"open":"close");int limit=clip==null?2:(int)Math.ceil(clip.seconds()*20)+2;for(int tick=0;object.animationBusy()&&tick<limit;tick++)object.tick();if(object.animationBusy())throw new AssertionError("Actual authored clip remains busy after its full duration");}
    private static RpObjectEntity object(TestContext c,String asset,int x){var rp=ObjectRegistry.TYPES.get(asset).create(c.getWorld());var root=c.getAbsolutePos(new BlockPos(x,2,1));rp.refreshPositionAndAngles(root.getX()+.5,root.getY(),root.getZ()+.5,0,0);c.getWorld().spawnEntity(rp);return rp;}
    private static void cleanup(ServerPlayerEntity p,RpObjectEntity... objects){for(var o:objects)o.removeByBuilder();p.discard();}
}
