package dev.dreamwalker.bloodbornerp.lamp;

import com.google.gson.*;
import com.mojang.authlib.GameProfile;
import dev.dreamwalker.bloodbornedw.architecture.*;
import dev.dreamwalker.bloodbornedw.composite.*;
import dev.dreamwalker.bloodbornedw.link.*;
import dev.dreamwalker.bloodbornerp.object.*;
import java.nio.file.*;
import java.util.*;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.event.lifecycle.v1.*;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.minecraft.block.*;
import net.minecraft.entity.Entity;
import net.minecraft.entity.MovementType;
import net.minecraft.item.*;
import net.minecraft.nbt.*;
import net.minecraft.network.*;
import net.minecraft.network.packet.Packet;
import net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket;
import net.minecraft.registry.Registries;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.network.*;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.test.*;
import net.minecraft.util.*;
import net.minecraft.util.hit.*;
import net.minecraft.util.math.*;
import net.minecraft.world.*;
import net.minecraft.world.gen.chunk.FlatChunkGenerator;

/** Explicit, optional QA stand. Production has no entrypoint, marker parser, fake player or fixture authoring. */
public final class V9GameplayReviewBootstrap implements ModInitializer {
    private static Session active;
    @Override public void onInitialize(){ServerLifecycleEvents.SERVER_STARTED.register(server->{Path input=Path.of("review-v9-gameplay-input.json");if(Files.isRegularFile(input))try{active=new Session(server,JsonParser.parseString(Files.readString(input)).getAsJsonObject());}catch(Throwable error){failure(error);}});ServerTickEvents.END_SERVER_TICK.register(server->{if(active!=null&&active.server==server)try{active.tick();}catch(Throwable error){active.fail(error);active=null;}});ServerLifecycleEvents.SERVER_STOPPED.register(server->{if(active!=null&&active.server==server)active=null;});}
    private static void failure(Throwable error){error.printStackTrace();JsonObject report=new JsonObject();report.addProperty("status","FAIL_V9_GAMEPLAY");report.addProperty("error",error.toString());write(report);}
    private static void write(JsonObject report){try{Files.writeString(Path.of("review-v9-gameplay-output.json"),new GsonBuilder().setPrettyPrinting().create().toJson(report));}catch(Exception error){throw new IllegalStateException(error);}}
    private static final class Session {
        final MinecraftServer server;final ServerWorld world;final JsonObject input,report=new JsonObject();final JsonArray checks=new JsonArray(),placements=new JsonArray();final boolean author;
        final Markers markers;final Map<String,RpObjectEntity> visuals=new LinkedHashMap<>();final Set<Long> temporaryForcedChunks=new LinkedHashSet<>();final JsonArray targetStates=new JsonArray(),leverOperations=new JsonArray();ServerPlayerEntity player;CapturingConnection connection;int started=-1,waitTicks;RpObjectEntity leverA,leverB,rpDoor,chest,gate,lampA,lampB;MechanismLinks.TargetRef architecturalDoor;boolean doorInitial,chestInitial,gateInitial,archInitial,ladderInitial;BlockPos respawnBefore;int healthBefore;UUID nodeA,nodeB;
        Session(MinecraftServer server,JsonObject input){
            this.server=server;this.world=server.getOverworld();this.input=input;author=input.get("phase").getAsString().equals("AUTHOR");
            require(input.has("productionGuard")&&input.get("productionGuard").getAsString().equals("QA_ONLY_SEPARATE_FRESH_OR_REOPENED_REVIEW_WORLD"),"explicit isolated gameplay QA guard");
            require(input.get("schemaVersion").getAsInt()==1&&Set.of("AUTHOR","REOPEN").contains(input.get("phase").getAsString()),"explicit V9 phase/schema required");
            require(server.getSaveProperties().getLevelName().equals(input.get("allowedLevelName").getAsString()),"isolated QA level name");
            require(world.getChunkManager().getChunkGenerator() instanceof FlatChunkGenerator,"fresh flat/reopened flat review only");
            require(!Files.exists(Path.of("review-v9-gameplay-output.json")),"fresh report path; no evidence overwrite");
            report.addProperty("schema","dreamwalker-v9-ordinary-rp-gameplay-v1");report.addProperty("phase",author?"AUTHOR":"REOPEN");report.addProperty("manual_visual_gameplay","NOT_RUN");report.addProperty("scope","Real production item/callback/entity/70-tick lever and lamp travel endpoint on a server survival QA player; no client GUI acceptance.");report.add("checks",checks);report.add("ordinaryItemPlacements",placements);report.add("actualTargetStates",targetStates);report.add("leverOperations",leverOperations);report.addProperty("fixtureTicking","BOUNDED_TEMPORARY_FORCED_CHUNKS_ORIGINAL_FORCED_FLAGS_RESTORED");
            markers=world.getPersistentStateManager().getOrCreate(Markers::read,Markers::new,"bloodborne_dw_v9_gameplay_review");
            if(author)require(markers.data.isEmpty(),"stand may be authored only once");else require(!markers.data.isEmpty(),"restart proof requires previously saved stand identities");
            for(String group:List.of("rpObjects","lamps","visualObjects"))if(input.has(group))for(JsonElement raw:input.getAsJsonArray(group))keepTicking(position(raw.getAsJsonObject().getAsJsonArray("root")));keepTicking(position(input.getAsJsonArray("architectureDoorRoot")));
        }
        void keepTicking(BlockPos pos){ChunkPos chunk=new ChunkPos(pos);if(!world.getForcedChunks().contains(chunk.toLong())){world.setChunkForced(chunk.x,chunk.z,true);temporaryForcedChunks.add(chunk.toLong());}world.getChunk(pos);}
        void tick(){
            if(started<0){if(++waitTicks<20)return;if(!author&&!loaded()){require(waitTicks<400,"persisted fixture UUIDs loaded within bounded warmup");return;}begin();started=server.getTicks();return;}
            int elapsed=server.getTicks()-started;
            if(elapsed<=34){player.setPosition(visuals.get("WoodGate").getX(),visuals.get("WoodGate").getY(),visuals.get("WoodGate").getZ()-2);visuals.get("WoodGate").interact(player,Hand.MAIN_HAND);}
            if(elapsed==34)check("heldWoodGateDoesNotQueueAnotherPulse",!visuals.get("WoodGate").woodGatePulseActive()&&!visuals.get("WoodGate").isOpen());
            if(elapsed==69){check("originalLeverDelay69",rpDoor.isOpen()==doorInitial&&chest.isOpen()==chestInitial&&gate.isOpen()==gateInitial&&archOpen()==archInitial);check("nativeLeverDelayIsOneAfter69EntityTicks",leverA.writeNbt(new NbtCompound()).getInt("LeverPulseTicks")==1&&leverA.age-leverOperations.get(0).getAsJsonObject().get("entityAge").getAsInt()==69);}
            if(elapsed==71){checkTargets(!doorInitial,!chestInitial,!gateInitial,!archInitial,"firstLeverActualTargets");operate(leverB);}
            if(elapsed==142){checkTargets(doorInitial,!chestInitial,!gateInitial,!archInitial,"secondLeverUsesSharedActualDoor");travel(lampB,nodeA,lampA,"reverseDirectedTravelAfterCooldown");operate(leverA);}
            if(elapsed==213){checkTargets(!doorInitial,chestInitial,gateInitial,archInitial,"primaryLeverSecondOperation");operate(leverB);}
            if(elapsed==284){checkTargets(doorInitial,chestInitial,gateInitial,archInitial,"allOrdinaryTargetStatesRestored");finish();active=null;}
        }
        boolean loaded(){for(String key:List.of("LeverA","LeverB","RpDoor","Chest","Gate","LampA","LampB"))if(!(world.getEntity(markers.data.getUuid(key)) instanceof RpObjectEntity))return false;NbtCompound visual=markers.data.getCompound("VisualObjects");for(String key:visual.getKeys())if(!(world.getEntity(visual.getUuid(key)) instanceof RpObjectEntity))return false;return true;}
        void begin(){
            player=new ServerPlayerEntity(server,world,new GameProfile(UUID.randomUUID(),"V9GameplayQA"));connection=new CapturingConnection();player.networkHandler=new ServerPlayNetworkHandler(server,connection,player);player.changeGameMode(GameMode.CREATIVE);player.getAbilities().allowModifyWorld=true;
            if(author){
                for(JsonElement raw:input.getAsJsonArray("foundationFills")){JsonObject fill=raw.getAsJsonObject();BlockPos from=position(fill.getAsJsonArray("from")),to=position(fill.getAsJsonArray("to"));require(from.getY()==63&&to.getY()==63,"stand foundation onlyY63");for(BlockPos pos:BlockPos.iterate(from,to)){world.getChunk(pos);require(world.getBlockState(pos).isAir()||world.getBlockState(pos).isOf(Blocks.GRASS_BLOCK)||world.getBlockState(pos).isOf(Blocks.SMOOTH_STONE),"fresh stand foundation cannot replace foreign block");world.setBlockState(pos,Blocks.SMOOTH_STONE.getDefaultState(),Block.NOTIFY_ALL);}}
                Map<String,RpObjectEntity> objects=new HashMap<>();for(JsonElement raw:input.getAsJsonArray("rpObjects")){JsonObject row=raw.getAsJsonObject();objects.put(row.get("role").getAsString(),place(row));}
                leverA=objects.get("LeverA");leverB=objects.get("LeverB");rpDoor=objects.get("RpDoor");chest=objects.get("Chest");gate=objects.get("Gate");
                if(input.has("nativeSupports"))for(JsonElement raw:input.getAsJsonArray("nativeSupports")){JsonObject row=raw.getAsJsonObject();BlockPos pos=position(row.getAsJsonArray("pos"));require(world.getBlockState(pos).isAir(),"new ceiling support cannot replace foreign block");world.setBlockState(pos,Registries.BLOCK.get(new Identifier(row.get("block").getAsString())).getDefaultState(),Block.NOTIFY_ALL);}
                NbtCompound visualIds=new NbtCompound();for(JsonElement raw:input.getAsJsonArray("visualObjects")){JsonObject row=raw.getAsJsonObject();String role=row.get("role").getAsString();RpObjectEntity entity=place(row);visuals.put(role,entity);visualIds.putUuid(role,entity.getUuid());if(row.has("dogsVisible")&&row.get("dogsVisible").getAsBoolean()!=entity.dogsVisible()){ItemStack dogTool=new ItemStack(PrototypeArchitecture.BUILDER_TOOL);dogTool.getOrCreateNbt().putInt("BuilderAction",BuildingTool.Action.DOGS.ordinal());player.setStackInHand(Hand.MAIN_HAND,dogTool);edit(entity);}if(row.has("dogsVisible"))check(role+"InstanceDogsFlag",entity.dogsVisible()==row.get("dogsVisible").getAsBoolean());}
                markers.data.put("VisualObjects",visualIds);check("sameCageTypeTwoIndependentVisibilityFlags",!visuals.get("CageHidden").dogsVisible()&&visuals.get("CageVisibleTwin").dogsVisible());
                JsonObject a=input.getAsJsonArray("lamps").get(0).getAsJsonObject(),b=input.getAsJsonArray("lamps").get(1).getAsJsonObject();lampA=place(a);lampB=place(b);aim(lampA);require(LampService.register(player,a.get("name").getAsString()),"first lamp registers through existing crosshair API");aim(lampB);require(LampService.register(player,b.get("name").getAsString()),"second lamp registers through existing crosshair API");
                nodeA=node(lampA).id;nodeB=node(lampB).id;require(LampService.route(server,nodeA,nodeB,true)&&LampService.route(server,nodeB,nodeA,true),"existing directed network gets explicit outbound and reverse routes");
                ItemStack tool=new ItemStack(PrototypeArchitecture.BUILDER_TOOL);tool.getOrCreateNbt().putInt("BuilderAction",BuildingTool.Action.LINK.ordinal());player.setStackInHand(Hand.MAIN_HAND,tool);edit(leverA);edit(rpDoor);edit(chest);edit(gate);
                BlockPos archRoot=position(input.getAsJsonArray("architectureDoorRoot"));require(world.getBlockEntity(archRoot) instanceof CompositeBlockEntity,"accepted architecture door fixture exists");var owner=((CompositeBlockEntity)world.getBlockEntity(archRoot)).resident();architecturalDoor=CompositeMechanismBridge.reference(world,owner);player.setPosition(archRoot.getX()+.5,archRoot.getY(),archRoot.getZ()-3);aimPoint(new Vec3d(archRoot.getX()+.5,archRoot.getY()+1.2,archRoot.getZ()+.125));HitResult ray=player.raycast(6,1,false);require(ray instanceof BlockHitResult hit&&ray.getType()==HitResult.Type.BLOCK&&tool.getItem().useOnBlock(new ItemUsageContext(player,Hand.MAIN_HAND,hit)).isAccepted(),"ordinary tool block callback links exact architecture owner");
                edit(leverB);edit(rpDoor);require(MechanismLinks.targets(leverA).size()==4&&MechanismLinks.targets(leverB).size()==1,"multiple target/source topology exact");
                edit(leverA);edit(visuals.get("RpLadder"));edit(visuals.get("WoodGate"));require(MechanismLinks.targets(leverA).size()==6,"original animated ladder and pulse-only gate links use real capabilities");
                for(var entry:Map.of("LeverA",leverA,"LeverB",leverB,"RpDoor",rpDoor,"Chest",chest,"Gate",gate,"LampA",lampA,"LampB",lampB).entrySet())markers.data.putUuid(entry.getKey(),entry.getValue().getUuid());markers.data.putUuid("NodeA",nodeA);markers.data.putUuid("NodeB",nodeB);markers.data.put("ArchitectureDoor",architecturalDoor.write());
            }else{
                leverA=entity("LeverA");leverB=entity("LeverB");rpDoor=entity("RpDoor");chest=entity("Chest");gate=entity("Gate");lampA=entity("LampA");lampB=entity("LampB");nodeA=markers.data.getUuid("NodeA");nodeB=markers.data.getUuid("NodeB");architecturalDoor=MechanismLinks.TargetRef.read(markers.data.getCompound("ArchitectureDoor"));
                NbtCompound ids=markers.data.getCompound("VisualObjects");for(String role:ids.getKeys())visuals.put(role,(RpObjectEntity)world.getEntity(ids.getUuid(role)));for(JsonElement raw:input.getAsJsonArray("visualObjects")){JsonObject row=raw.getAsJsonObject();RpObjectEntity entity=visuals.get(row.get("role").getAsString());require(entity.assetId().equals(row.get("asset").getAsString()),"persisted visual object UUID/type");if(row.has("dogsVisible"))check(row.get("role").getAsString()+"PersistedDogVisibility",entity.dogsVisible()==row.get("dogsVisible").getAsBoolean());}
                check("persistedExactLampNodeAndEntityIdentities",node(lampA).id.equals(nodeA)&&node(lampB).id.equals(nodeB));check("persistedBothDirectedRoutes",node(lampA).routes.equals(List.of(nodeB))&&node(lampB).routes.equals(List.of(nodeA)));check("persistedLinksAndArchitectureOwner",MechanismLinks.targets(leverA).size()==6&&MechanismLinks.targets(leverB).size()==1&&MechanismLinks.targets(leverA).contains(architecturalDoor));check("woodGateRestartsIdleWithoutSavedRequest",!visuals.get("WoodGate").woodGatePulseActive()&&!visuals.get("WoodGate").isOpen());
            }
            doorInitial=rpDoor.isOpen();chestInitial=chest.isOpen();gateInitial=gate.isOpen();archInitial=archOpen();ladderInitial=visuals.get("RpLadder").isOpen();require(!leverA.isOpen()&&!leverB.isOpen(),"both levers resume idle after restart");
            player.setStackInHand(Hand.MAIN_HAND,ItemStack.EMPTY);player.changeGameMode(GameMode.SURVIVAL);require(!player.isCreative()&&!player.isSpectator(),"ordinary survival actor");respawnBefore=player.getSpawnPointPosition();healthBefore=Float.floatToIntBits(player.getHealth());travel(lampA,nodeB,lampB,"outboundDirectedTravel");operate(leverA);
            player.setPosition(visuals.get("WoodGate").getX(),visuals.get("WoodGate").getY(),visuals.get("WoodGate").getZ()-2);require(visuals.get("WoodGate").interact(player,Hand.MAIN_HAND).isAccepted(),"one ordinary woodgate click starts source32-tick clip");check("woodGateRejectsOffhandAndInflightRepeat",!visuals.get("WoodGate").interact(player,Hand.OFF_HAND).isAccepted()&&!visuals.get("WoodGate").interact(player,Hand.MAIN_HAND).isAccepted());
        }
        RpObjectEntity place(JsonObject row){
            String asset=row.get("asset").getAsString();BlockPos root=position(row.getAsJsonArray("root"));player.setPosition(root.getX()+.5,root.getY(),root.getZ()-6);float yaw=row.has("yawOverride")?row.get("yawOverride").getAsFloat():180;player.setYaw(yaw);player.setHeadYaw(yaw);player.setPitch(0);
            Item item=Registries.ITEM.get(new Identifier("bloodborne_rp",asset+"_placer"));ItemStack stack=new ItemStack(item);player.setStackInHand(Hand.MAIN_HAND,stack);Set<UUID> before=new HashSet<>();for(Entity entity:world.iterateEntities())before.add(entity.getUuid());
            Direction face=row.has("mountFace")?Direction.valueOf(row.get("mountFace").getAsString().toUpperCase(Locale.ROOT)):Direction.UP;BlockPos clicked=row.has("clicked")?position(row.getAsJsonArray("clicked")):root.down();
            ActionResult result=item.useOnBlock(new ItemUsageContext(player,Hand.MAIN_HAND,new BlockHitResult(Vec3d.ofCenter(clicked).add(Vec3d.of(face.getVector()).multiply(.5)),face,clicked,false)));require(result.isAccepted(),"ordinary RP placer accepts "+asset);
            RpObjectEntity entity=null;for(Entity candidate:world.iterateEntities())if(candidate instanceof RpObjectEntity rp&&!before.contains(candidate.getUuid())&&rp.assetId().equals(asset)){require(entity==null,"exactly one entity per item placement");entity=rp;}require(entity!=null,"RP item produces requested entity");
            JsonObject proof=row.deepCopy();proof.addProperty("uuid",entity.getUuid().toString());proof.addProperty("itemPath","Item.useOnBlock");proof.addProperty("action",result.toString());proof.addProperty("actualY",entity.getY());placements.add(proof);return entity;
        }
        void edit(RpObjectEntity target){aim(target);require(UseEntityCallback.EVENT.invoker().interact(player,world,Hand.MAIN_HAND,target,null).isAccepted(),"ordinary entity builder callback "+target.assetId());}
        void operate(RpObjectEntity lever){player.setPosition(lever.getX(),lever.getY(),lever.getZ()+2);player.setStackInHand(Hand.MAIN_HAND,ItemStack.EMPTY);require(lever.interact(player,Hand.MAIN_HAND).isAccepted(),"ordinary lever interaction accepted");JsonObject row=new JsonObject();row.addProperty("uuid",lever.getUuid().toString());row.addProperty("serverTick",server.getTicks());row.addProperty("entityAge",lever.age);row.addProperty("nativeRemainingDelay",lever.writeNbt(new NbtCompound()).getInt("LeverPulseTicks"));leverOperations.add(row);}
        void travel(RpObjectEntity source,UUID destination,RpObjectEntity target,String check){
            player.setPosition(source.getX(),source.getY(),source.getZ()+2);connection.packets.clear();require(source.interact(player,Hand.MAIN_HAND).isAccepted(),"ordinary lamp opens existing travel UI packet");long token=LampService.contextTokenForTest(player.getUuid());require(token!=Long.MIN_VALUE,"live lamp context exists");boolean packetVerified=false;
            for(Packet<?> packet:connection.packets)if(packet instanceof CustomPayloadS2CPacket payload&&payload.getChannel().equals(LampService.LIST_PACKET)){PacketByteBuf data=new PacketByteBuf(payload.getData().copy());long sent=data.readLong();int count=data.readVarInt();require(sent==token&&count==1,"opaque context and one registered destination sent to client");UUID id=data.readUuid();String name=data.readString(64);require(id.equals(destination)&&!name.isBlank(),"destination UUID/name matches existing directed route");data.release();packetVerified=true;}
            require(packetVerified,"real server travel list packet captured");Vec3d before=player.getPos();require(LampService.travelForTest(player,destination,token),"existing opaque-context travel endpoint accepted");check(check,player.squaredDistanceTo(target)<=25&&player.getPos().squaredDistanceTo(before)>100);check(check+"ReplayRejected",!LampService.travelForTest(player,destination,token));
        }
        void aim(RpObjectEntity entity){player.setPosition(entity.getX(),entity.getY(),entity.getZ()-2);aimPoint(entity.getBoundingBox().getCenter());}
        void aimPoint(Vec3d target){Vec3d delta=target.subtract(player.getEyePos());float yaw=(float)Math.toDegrees(Math.atan2(-delta.x,delta.z)),pitch=(float)-Math.toDegrees(Math.atan2(delta.y,Math.sqrt(delta.x*delta.x+delta.z*delta.z)));player.setYaw(yaw);player.setHeadYaw(yaw);player.setPitch(pitch);}
        LampState.Node node(RpObjectEntity lamp){return LampState.get(server.getOverworld()).nodes.values().stream().filter(n->n.lamp.equals(lamp.getUuid())).findFirst().orElseThrow(()->new IllegalStateException("registered lamp UUID missing"));}
        RpObjectEntity entity(String key){Entity entity=world.getEntity(markers.data.getUuid(key));require(entity instanceof RpObjectEntity,"saved object UUID exists:"+key);return (RpObjectEntity)entity;}
        boolean archOpen(){var status=MechanismLinks.inspect(server,architecturalDoor);require(status.availability()==MechanismLinks.Availability.LOADED,"exact architectural owner remains loaded");return status.open();}
        void checkTargets(boolean door,boolean box,boolean doorGate,boolean arch,String name){boolean actualArch=archOpen();JsonObject row=new JsonObject();row.addProperty("phase",name);row.addProperty("elapsedServerTicks",server.getTicks()-started);row.addProperty("rpDoor",rpDoor.isOpen());row.addProperty("chest",chest.isOpen());row.addProperty("gate",gate.isOpen());row.addProperty("architectureDoor",actualArch);row.addProperty("architecturePending",MechanismLinks.pending(server,architecturalDoor));row.addProperty("leverAAge",leverA.age);row.addProperty("leverBAge",leverB.age);row.addProperty("leverARemainingDelay",leverA.writeNbt(new NbtCompound()).getInt("LeverPulseTicks"));row.addProperty("leverBRemainingDelay",leverB.writeNbt(new NbtCompound()).getInt("LeverPulseTicks"));targetStates.add(row);check(name,rpDoor.isOpen()==door&&chest.isOpen()==box&&gate.isOpen()==doorGate&&actualArch==arch);check(name+"RpCollision",rpDoor.isCollidable()!=door&&gate.isCollidable()!=doorGate);if(name.equals("firstLeverActualTargets")||name.equals("secondLeverUsesSharedActualDoor"))check(name+"OriginalRpLadderActivated",visuals.get("RpLadder").isOpen()!=ladderInitial);if(name.equals("allOrdinaryTargetStatesRestored")){check("originalRpLadderStateRestored",visuals.get("RpLadder").isOpen()==ladderInitial);check("bothNativeLeverDelaysFinishedBeforeSave",!leverA.isOpen()&&!leverB.isOpen());}}
        void check(String name,boolean pass){JsonObject row=new JsonObject();row.addProperty("check",name);row.addProperty("pass",pass);checks.add(row);require(pass,name);}
        void finish(){
            movementProbes();
            check("noRespawnPointOrHealthChange",Objects.equals(respawnBefore,player.getSpawnPointPosition())&&healthBefore==Float.floatToIntBits(player.getHealth()));check("newLampDoesNotInventTechnicalLighting",world.getBlockState(lampA.getBlockPos()).isAir()&&world.getBlockState(lampB.getBlockPos()).isAir());
            check("pulseOnlyLinkedWoodgateReturnsIdleWithoutFakeOpen",!visuals.get("WoodGate").woodGatePulseActive()&&!visuals.get("WoodGate").isOpen());JsonArray costs=new JsonArray();for(var entry:visuals.entrySet()){JsonObject row=new JsonObject();row.addProperty("role",entry.getKey());row.addProperty("uuid",entry.getValue().getUuid().toString());row.addProperty("physicalBoxes",entry.getValue().activePhysicalBoxes().size());row.addProperty("selectionBoxes",entry.getValue().selectionBoxes().size());row.addProperty("visualBounds",entry.getValue().visualBounds().toString());row.addProperty("dogsVisible",entry.getValue().dogsVisible());costs.add(row);}report.add("actualRpPhysicsSelectionCost",costs);
            markers.data.putBoolean("AuthorPassed",true);markers.data.putBoolean("RestartPassed",!author||markers.data.getBoolean("RestartPassed"));markers.markDirty();report.addProperty("status",author?"PASS_V9_ORDINARY_GAMEPLAY_AUTHOR_REQUIRES_ACTUAL_RESTART":"PASS_V9_ORDINARY_GAMEPLAY_AFTER_ACTUAL_RESTART");report.addProperty("identities",markers.data.toString());report.addProperty("leverDelayTicks",70);report.addProperty("elapsedServerTicks",server.getTicks()-started);report.addProperty("hunterlampTravel","PASS_EXISTING_DIRECTED_NETWORK_BOTH_DIRECTIONS");report.addProperty("newLampLighting","UNCHANGED_NO_AUTOMATIC_SOURCE_TECHNICAL_LIGHT");report.addProperty("respawn","UNCHANGED_NO_NEW_FEATURE");cleanupPlayer();write(report);System.out.println("Dreamwalker V9 ordinary gameplay: "+report.get("status"));
        }
        void movementProbes(){
            JsonArray movements=new JsonArray();report.add("actualMovementProbes",movements);
            for(String role:List.of("NpcWindow","WoodGate")){
                RpObjectEntity entity=visuals.get(role);require(entity.activePhysicalBoxes().size()==1&&entity.hasCustomPhysicalGeometry()&&!entity.isCollidable(),"one local working plane avoids a giant native entity collider:"+role);Box box=entity.activePhysicalBoxes().get(0);boolean normalX=box.getXLength()<box.getZLength();Vec3d normal=normalX?new Vec3d(1,0,0):new Vec3d(0,0,1),wide=normalX?new Vec3d(0,0,1):new Vec3d(1,0,0);Vec3d center=new Vec3d((box.minX+box.maxX)/2,box.minY+.2,(box.minZ+box.maxZ)/2);
                for(int sign:List.of(-1,1)){Vec3d start=center.add(normal.multiply(sign*3)),wanted=normal.multiply(-sign*6);Vec3d actual=moveProbe(movements,role+"-side-"+sign,start,wanted);check(role+"ActualPlayerBlocksSide"+sign,actual.length()<3);}
                double width=normalX?box.getZLength():box.getXLength();Vec3d outside=center.add(wide.multiply(width/2+2)).subtract(normal.multiply(3));Vec3d actual=moveProbe(movements,role+"-outside-working-edge",outside,normal.multiply(6));check(role+"OutsideWorkingPlanePassable",actual.squaredDistanceTo(normal.multiply(6))<1e-8);
            }
            for(String role:List.of("ChandelierFloor","ChandelierCeiling")){RpObjectEntity entity=visuals.get(role);Box visual=entity.visualBounds();Vec3d center=visual.getCenter();Vec3d start=new Vec3d(center.x,Math.max(visual.minY+.1,center.y-.9),visual.minZ-1);player.setPosition(start);check(role+"NoDecorativeAabbPhysics",entity.activePhysicalBoxes().isEmpty()&&world.getEntityCollisions(player,player.getBoundingBox().stretch(0,0,visual.getZLength()+2)).isEmpty());Vec3d wanted=new Vec3d(0,0,visual.getZLength()+2);check(role+"ActualPlayerCrossesDecor",moveProbe(movements,role+"-through-visible-decor",start,wanted).squaredDistanceTo(wanted)<1e-8);}
            RpObjectEntity ladder=visuals.get("RpLadder");Box lower=ladder.climbingBoxes().stream().min(Comparator.comparingDouble(box->box.minY)).orElseThrow();Vec3d foot=new Vec3d(lower.getCenter().x,lower.minY+1.5,lower.getCenter().z);player.setPosition(foot);player.setVelocity(Vec3d.ZERO);check("RpLadderActualWorkingFootClimbsFarBelowOrigin",ladder.isOpen()&&ladder.getY()-player.getY()>27&&player.isClimbing());Box working=ladder.activePhysicalBoxes().stream().min(Comparator.comparingDouble(box->box.minY)).orElseThrow();Box query=new Box(working.minX-.01,foot.y,working.minZ-.01,working.maxX+.01,foot.y+.4,working.maxZ+.01);var collisions=world.getEntityCollisions(player,query);check("RpLadderWorldQueriesActualThinLowerPanel",!collisions.isEmpty()&&collisions.stream().flatMap(shape->shape.getBoundingBoxes().stream()).allMatch(box->Math.min(box.getXLength(),box.getZLength())<=.126));JsonObject lowerProof=new JsonObject();lowerProof.addProperty("probe","RpLadder-working-foot");lowerProof.add("player",vector(foot));lowerProof.addProperty("originHeightDelta",ladder.getY()-player.getY());lowerProof.addProperty("climbing",player.isClimbing());lowerProof.addProperty("nativeEntityCollisionShapeCount",collisions.size());movements.add(lowerProof);
            RpObjectEntity stairs=visuals.get("RpStairs");Box first=stairs.activePhysicalBoxes().stream().min(Comparator.<Box>comparingDouble(box->box.minY).thenComparingDouble(box->box.maxY)).orElseThrow();Vec3d facing=RpObjectGeometry.rotate(new Vec3d(0,0,1),stairs.getYaw());double front=facing.x>0.5?first.minX:facing.x<-.5?first.maxX:facing.z>0.5?first.minZ:first.maxZ;Vec3d start=new Vec3d(first.getCenter().x,first.minY+.05,first.getCenter().z);start=Math.abs(facing.x)>.5?new Vec3d(front,start.y,start.z):new Vec3d(start.x,start.y,front);start=start.subtract(facing.multiply(.55));player.setPosition(start);player.setVelocity(Vec3d.ZERO);player.move(MovementType.SELF,new Vec3d(0,-.1,0));player.setOnGround(true);Vec3d grounded=player.getPos();double depth=Math.abs(facing.x)>.5?first.getXLength():first.getZLength();require(.4+player.getWidth()/2d-.55<depth-1e-6,"first-tread probe body cannot reach the next riser");Vec3d wanted=facing.multiply(.4).add(0,-.08,0);Vec3d actual=moveProbe(movements,"RpStairs-first-native-step",grounded,wanted);JsonObject treadProof=movements.get(movements.size()-1).getAsJsonObject();treadProof.addProperty("firstTreadTopY",first.maxY);treadProof.addProperty("firstTreadDepth",depth);treadProof.addProperty("playerBodyForwardExtentFromFirstFront",.4+player.getWidth()/2d-.55);check("RpStairsActualPlayerStepsFirstAuthoredTread",Math.abs(actual.dotProduct(facing)-.4)<1e-6&&Math.abs(actual.y-.5)<1e-6&&Math.abs(player.getY()-first.maxY)<1e-6);
            check("TwoSameCagesHaveIndependentFlagsAndUnchangedPhysicalCost",!visuals.get("CageHidden").dogsVisible()&&visuals.get("CageVisibleTwin").dogsVisible()&&visuals.get("CageHidden").activePhysicalBoxes().size()==visuals.get("CageVisibleTwin").activePhysicalBoxes().size());
        }
        Vec3d moveProbe(JsonArray proofs,String label,Vec3d start,Vec3d wanted){player.setPosition(start);player.setVelocity(Vec3d.ZERO);Box swept=player.getBoundingBox().stretch(wanted).expand(1e-7);var directShapes=world.getEntityCollisions(player,swept);JsonObject flags=new JsonObject();flags.addProperty("noClip",player.noClip);flags.addProperty("spectator",player.isSpectator());flags.addProperty("creative",player.isCreative());flags.addProperty("flying",player.getAbilities().flying);flags.addProperty("allowFlying",player.getAbilities().allowFlying);flags.addProperty("stepHeight",player.getStepHeight());flags.addProperty("onGround",player.isOnGround());JsonArray indexed=new JsonArray();for(RpObjectEntity candidate:RpObjectIndex.in(world,swept)){JsonObject entry=new JsonObject();entry.addProperty("uuid",candidate.getUuid().toString());entry.addProperty("asset",candidate.assetId());entry.addProperty("activePhysicalBoxes",candidate.activePhysicalBoxes().size());indexed.add(entry);}player.move(MovementType.SELF,wanted);Vec3d actual=player.getPos().subtract(start);JsonObject row=new JsonObject();row.addProperty("probe",label);row.add("start",vector(start));row.add("requested",vector(wanted));row.add("actual",vector(actual));row.add("end",vector(player.getPos()));row.add("playerFlags",flags);row.addProperty("sweptQuery",swept.toString());row.addProperty("directWorldEntityCollisionShapes",directShapes.size());row.addProperty("directWorldEntityCollisionBoxes",directShapes.stream().mapToInt(shape->shape.getBoundingBoxes().size()).sum());row.add("rpIndexCandidates",indexed);proofs.add(row);return actual;}
        JsonArray vector(Vec3d value){JsonArray out=new JsonArray();out.add(value.x);out.add(value.y);out.add(value.z);return out;}
        void fail(Throwable error){error.printStackTrace();report.addProperty("status","FAIL_V9_GAMEPLAY");report.addProperty("error",error.toString());cleanupPlayer();write(report);}
        void cleanupPlayer(){if(player!=null){LampService.clearPlayerForTest(player.getUuid());player.discard();}for(long packed:temporaryForcedChunks){ChunkPos chunk=new ChunkPos(packed);world.setChunkForced(chunk.x,chunk.z,false);}temporaryForcedChunks.clear();report.addProperty("temporaryFixtureTickingTicketsRestored",true);}
    }
    private static final class CapturingConnection extends ClientConnection {final List<Packet<?>> packets=new ArrayList<>();CapturingConnection(){super(NetworkSide.SERVERBOUND);}@Override public void send(Packet<?> packet){packets.add(packet);}@Override public void send(Packet<?> packet,PacketCallbacks callbacks){packets.add(packet);}}
    private static final class Markers extends PersistentState {NbtCompound data=new NbtCompound();static Markers read(NbtCompound tag){Markers markers=new Markers();if(tag.getInt("Schema")==1)markers.data=tag.getCompound("Data").copy();return markers;}@Override public NbtCompound writeNbt(NbtCompound tag){tag.putInt("Schema",1);tag.put("Data",data.copy());return tag;}}
    private static BlockPos position(JsonArray array){require(array.size()==3,"three integer coordinates");BlockPos pos=new BlockPos(array.get(0).getAsInt(),array.get(1).getAsInt(),array.get(2).getAsInt());require(Math.abs(pos.getX())<=96&&Math.abs(pos.getZ())<=96&&pos.getY()>=63&&pos.getY()<=100,"bounded new review coordinate");return pos;}
    private static void require(boolean value,String message){if(!value)throw new IllegalStateException(message);}
}
