package dev.dreamwalker.bloodbornedw.tool;

import com.google.gson.*;
import dev.dreamwalker.bloodbornedw.architecture.*;
import dev.dreamwalker.bloodbornedw.architecture.mount.VerticalMount;
import dev.dreamwalker.bloodbornedw.architecture.ladder_source.SourceLadderRuntime;
import dev.dreamwalker.bloodbornedw.architecture.wall.*;
import dev.dreamwalker.bloodbornedw.composite.*;
import dev.dreamwalker.bloodbornedw.debug.DebugCatalogue;
import dev.dreamwalker.bloodbornedw.diagnostics.DwDiagnostics;
import dev.dreamwalker.bloodbornedw.link.*;
import dev.dreamwalker.bloodbornedw.runtime.TransactionCore;
import dev.dreamwalker.bloodbornerp.lamp.LampEditor;
import dev.dreamwalker.bloodbornerp.object.RpObjectEntity;
import java.util.*;
import net.fabricmc.fabric.api.networking.v1.*;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.minecraft.block.BlockState;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.*;
import net.minecraft.util.hit.*;
import net.minecraft.util.math.*;

/** Every GUI mutation is resolved and authorised again on the server thread. */
public final class BuilderServer {
    public static final Identifier REQUEST=new Identifier("bloodborne_dw","builder_request"),VIEW=new Identifier("bloodborne_dw","builder_view");
    public static final int MAX_REQUEST=12000,MAX_VIEW=300000;
    private static final Gson JSON=new Gson();
    private static final java.util.concurrent.ConcurrentHashMap<UUID,java.util.concurrent.atomic.AtomicInteger> REQUEST_PENDING=new java.util.concurrent.ConcurrentHashMap<>();
    private static final Map<UUID,Session> SESSIONS=new HashMap<>();
    private static boolean initialized;
    private static final class Session { MechanismLinks.TargetRef target;boolean pinned;long expires;int lastClick=-100,lampPage,rulePage,affectedPage;UUID rule;final Set<UUID> editable=new LinkedHashSet<>();List<MechanismLinks.TargetRef> candidates=List.of();String message=""; }
    private BuilderServer(){}
    public static void initialize(){if(initialized)return;initialized=true;
        ServerPlayNetworking.registerGlobalReceiver(REQUEST,(server,player,handler,buf,sender)->{int size=buf.readableBytes();String raw;try{raw=buf.readString(MAX_REQUEST);}catch(RuntimeException invalid){return;}DwDiagnostics.network("server","receive",REQUEST.toString(),size);var pending=REQUEST_PENDING.computeIfAbsent(player.getUuid(),id->new java.util.concurrent.atomic.AtomicInteger());if(pending.incrementAndGet()>4){pending.decrementAndGet();return;}server.execute(()->{try{request(player,JsonParser.parseString(raw).getAsJsonObject());}catch(RuntimeException invalid){DwDiagnostics.error(player.getServerWorld(),"UNASSIGNED",player.getUuidAsString(),player.getBlockPos(),"BUILDER_REQUEST","Rejected invalid builder request",invalid);notice(player,"Некорректные параметры меню.");}finally{pending.decrementAndGet();}});});
        ServerPlayConnectionEvents.DISCONNECT.register((handler,server)->clearPlayer(handler.player.getUuid()));ServerLifecycleEvents.SERVER_STOPPED.register(server->{SESSIONS.clear();REQUEST_PENDING.clear();});
    }
    private static void clearPlayer(UUID id){SESSIONS.remove(id);REQUEST_PENDING.remove(id);}
    private static Session session(ServerPlayerEntity player){if(SESSIONS.size()>=256&&!SESSIONS.containsKey(player.getUuid()))SESSIONS.remove(SESSIONS.keySet().iterator().next());Session s=SESSIONS.computeIfAbsent(player.getUuid(),i->new Session());if(s.expires<player.getServer().getTicks()){s.target=null;s.pinned=false;s.rule=null;s.editable.clear();}s.expires=player.getServer().getTicks()+12000;return s;}
    public static void open(ServerPlayerEntity player){if(!BuildingTool.mainHeld(player))return;dev.dreamwalker.bloodbornerp.lamp.LampService.cancelTravel(player);Session s=session(player);s.candidates=candidates(player);if(!s.candidates.isEmpty()){s.target=s.candidates.get(0);s.pinned=false;}restoreRule(player,s);send(player,s,true);}
    private static void restoreRule(ServerPlayerEntity p,Session s){var n=p.getMainHandStack().getOrCreateNbt();if(n.containsUuid("BuilderRule")){UUID id=n.getUuid("BuilderRule");if(s.editable.contains(id)||allowedRule(p,s,id))s.rule=id;}}
    private static boolean allowedRule(ServerPlayerEntity p,Session s,UUID id){var r=MechanismRules.rule(p.getServer(),id);return r!=null&&(s.editable.contains(id)||s.target!=null&&(r.targets.containsKey(s.target.key())||r.sources.containsKey(s.target.instance())));}
    private static void request(ServerPlayerEntity p,JsonObject q){if(!BuildingTool.isHeld(p))return;Session s=session(p);String op=text(q,"op",40);
        if(op.equals("click")){click(p,s);return;}if(!BuildingTool.mainHeld(p)){notice(p,"Перенесите строительный инструмент в основную руку.");return;}
        if(op.equals("open")){open(p);return;}if(op.equals("refresh")){send(p,s,false);return;}
        if(!BuildPermissions.canEdit(p)){notice(p,"Редактирование доступно в Creative или оператору.");send(p,s,false);return;}
        ItemStack tool=p.getMainHandStack();
        switch(op){
            case "mode" -> {BuildingTool.Action action=BuildingTool.Action.valueOf(text(q,"action",40));tool.getOrCreateNbt().putInt("BuilderAction",action.ordinal());if(action==BuildingTool.Action.LAMP_TARGET&&q.has("line")){tool.getOrCreateNbt().putString("BuilderLampLine",text(q,"line",64));tool.getOrCreateNbt().putBoolean("BuilderLampOneWay",!q.get("both").getAsBoolean());}s.message="Действие выбрано: "+action.label;}
            case "step" -> {double step=q.get("value").getAsDouble();if(step!=.0625&&step!=.125&&step!=.25&&step!=1)throw new IllegalArgumentException("step");tool.getOrCreateNbt().putDouble("BuilderStep",step);}
            case "select" -> {String key=text(q,"key",256);s.candidates=candidates(p);s.target=s.candidates.stream().filter(t->t.key().equals(key)).findFirst().orElse(null);s.pinned=s.target!=null;s.message=s.target==null?"Объект больше не находится под прицелом.":"Выбор закреплён.";}
            case "cancel_selection" -> {s.target=null;s.pinned=false;s.rule=null;tool.getOrCreateNbt().remove("BuilderRule");LampEditor.edit(p,new LampEditor.Request(LampEditor.Action.CANCEL,null,null,"","",true));s.message="Рабочий выбор отменён; готовые связи сохранены.";}
            case "object" -> objectForm(p,s,q);
            case "rule_create" -> {var r=MechanismRules.create(p,text(q,"name",80));if(r!=null){s.rule=r.id;if(s.editable.size()>=64)s.editable.remove(s.editable.iterator().next());s.editable.add(r.id);tool.getOrCreateNbt().putUuid("BuilderRule",r.id);s.message="1. Выберите источники; 2. Добавьте цели; 3. Завершите.";}}
            case "rule_select" -> {UUID id=UUID.fromString(text(q,"id",40));if(allowedRule(p,s,id)){s.rule=id;s.editable.add(id);tool.getOrCreateNbt().putUuid("BuilderRule",id);}}
            case "rule_apply" -> {if(ruleAllowed(p,s)){boolean done=MechanismRules.configure(p,s.rule,text(q,"name",80),MechanismRules.Condition.valueOf(text(q,"condition",10)),MechanismRules.Effect.valueOf(text(q,"effect",10)));s.message=done?"Настройка сохранена; игровых срабатываний не было.":"Эта настройка не поддерживается составом целей.";}}
            case "rule_remove_member" -> {if(ruleAllowed(p,s))MechanismRules.removeMember(p,s.rule,text(q,"key",256),q.get("source").getAsBoolean());}
            case "rule_reset" -> {if(ruleAllowed(p,s)&&q.has("confirmed")&&q.get("confirmed").getAsBoolean()){MechanismRules.reset(p,s.rule);s.message="Общие признаки сброшены; группы «Все» пересчитаны.";}}
            case "rule_delete" -> {if(ruleAllowed(p,s)&&q.has("confirmed")&&q.get("confirmed").getAsBoolean()){MechanismRules.delete(p,s.rule);s.rule=null;tool.getOrCreateNbt().remove("BuilderRule");s.message="Правило удалено.";}}
            case "commands" -> {if(validTarget(p,s)&&p.hasPermissionLevel(4)){List<String> lines=new ArrayList<>();for(JsonElement line:q.getAsJsonArray("commands")){if(lines.size()>=32)throw new IllegalArgumentException("commands");lines.add(line.getAsString());}s.message=ObjectPolicies.setCommands(p,s.target,q.get("open").getAsBoolean(),lines)?"Список команд сохранён.":"Нужен действительно открываемый объект и права администратора уровня 4.";}}
            case "rule_page" -> {s.rulePage=Math.max(0,Math.min(63,q.get("page").getAsInt()));}
            case "affected_page" -> {s.affectedPage=Math.max(0,Math.min(63,q.get("page").getAsInt()));}
            case "lamp_page" -> {s.lampPage=Math.max(0,Math.min(1023,q.get("page").getAsInt()));}
            case "lamp_parameters" -> {String line=text(q,"line",64);if(line.isBlank())throw new IllegalArgumentException("line");tool.getOrCreateNbt().putString("BuilderLampLine",line);tool.getOrCreateNbt().putBoolean("BuilderLampOneWay",!q.get("both").getAsBoolean());s.message="Параметры следующего назначения сохранены.";}
            case "lamp" -> lampForm(p,s,q);
            case "diagnostics" -> diagnostics(p,s,q);
            default -> throw new IllegalArgumentException("Unknown builder operation");
        }
        p.getInventory().markDirty();send(p,s,false);
    }
    private static boolean ruleAllowed(ServerPlayerEntity p,Session s){return s.rule!=null&&allowedRule(p,s,s.rule);}
    private static void click(ServerPlayerEntity p,Session s){
        if(!BuildingTool.mainHeld(p)){notice(p,"Перенесите строительный инструмент в основную руку.");return;}if(!BuildPermissions.canEdit(p)){notice(p,"Редактирование доступно в Creative или оператору.");return;}
        if(s.lastClick==p.getServer().getTicks())return;s.lastClick=p.getServer().getTicks();List<MechanismLinks.TargetRef> hits=candidates(p);s.candidates=hits;var target=s.target!=null&&hits.stream().anyMatch(t->t.key().equals(s.target.key()))?s.target:hits.isEmpty()?null:hits.get(0);
        if(target==null){notice(p,"Под прицелом нет подходящего объекта мода. Разрушение отменено.");return;}s.target=target;s.pinned=true;BuildingTool.Action action=BuildingTool.action(p.getMainHandStack());boolean done=true;
        if(action==BuildingTool.Action.SELECT||action==BuildingTool.Action.CONNECTIONS){s.message="Объект выбран. ПКМ — меню.";}
        else if(action==BuildingTool.Action.UP||action==BuildingTool.Action.DOWN){double current=offset(p,target),step=step(p.getMainHandStack());done=setOffset(p,target,current+(action==BuildingTool.Action.UP?step:-step));s.message=done?"Монтажное смещение: "+offset(p,target):"Не удалось изменить высоту в пределах мира.";}
        else if(action==BuildingTool.Action.RULE_SOURCE||action==BuildingTool.Action.RULE_TARGET){done=ruleAllowed(p,s)&&MechanismRules.add(p,s.rule,target,action==BuildingTool.Action.RULE_SOURCE);s.message=done?"Участник добавлен; выбранное правило сохранено.":"Сначала создайте правило и выберите подходящий источник/цель.";}
        else if(action==BuildingTool.Action.LAMP_SOURCE){var result=LampEditor.selectSource(p,target.kind()==MechanismLinks.Kind.RP?target.instance():null);s.message=result.reason();done=result.success();}
        else if(action==BuildingTool.Action.LAMP_TARGET){String line=p.getMainHandStack().getOrCreateNbt().getString("BuilderLampLine");if(line.isBlank())line="Охотничья линия";boolean both=!p.getMainHandStack().getOrCreateNbt().getBoolean("BuilderLampOneWay");var result=LampEditor.edit(p,new LampEditor.Request(LampEditor.Action.CONNECT,null,target.kind()==MechanismLinks.Kind.RP?target.instance():null,line,"",both));s.message=result.reason();done=result.success();}
        else if(action==BuildingTool.Action.DIAGNOSTICS){if(p.hasPermissionLevel(2)){snapshot(p,target,"Снимок инструментом");s.message="Снимок сохранён, объект не изменён.";}else{s.message="Диагностика доступна оператору уровня 2.";done=false;}}
        else if(target.kind()==MechanismLinks.Kind.RP){Entity entity=p.getServerWorld().getEntity(target.instance());done=entity instanceof RpObjectEntity rp&&MechanismBuilder.entity(p,p.getMainHandStack(),rp).isAccepted();if(!done)s.message="Этот RP-объект не поддерживает действие: "+action.label;}
        else{done=BuildingTool.applyBlock(p,BlockPos.fromLong(target.root()),action).isAccepted();if(!done)s.message="Этот блок не поддерживает действие или изменение отклонено: "+action.label;}
        notice(p,s.message);send(p,s,false);
    }
    public static double step(ItemStack stack){double value=stack.getOrCreateNbt().getDouble("BuilderStep");return value==.0625||value==.125||value==.25||value==1?value:.125;}
    private static boolean validTarget(ServerPlayerEntity p,Session s){return s.target!=null&&near(p,s.target)&&BuildPermissions.canEdit(p.getWorld(),p,BlockPos.fromLong(s.target.root()));}
    private static boolean near(ServerPlayerEntity p,MechanismLinks.TargetRef t){if(!t.dimension().equals(p.getWorld().getRegistryKey().getValue().toString()))return false;Vec3d eye=p.getEyePos();if(t.kind()==MechanismLinks.Kind.RP){Entity e=p.getServerWorld().getEntity(t.instance());return e instanceof RpObjectEntity rp&&!rp.isRemoved()&&rp.assetId().equals(t.registryId())&&rp.selectionBoxes().stream().anyMatch(b->distance(eye,b)<=36);}
        BlockPos root=BlockPos.fromLong(t.root());if(!p.getWorld().isChunkLoaded(root))return false;var owner=VerticalMount.owner(p.getWorld(),root);if(owner==null||!owner.instanceId().equals(t.instance())||!owner.registryId().equals(t.registryId()))return false;for(var cell:CompositeLedger.get(p.getWorld()).cells())for(var c:CompositeLedger.get(p.getWorld()).at(cell))if(c.owner().equals(owner))for(var box:CompositeRuntime.shape(c.shape().selection()).getBoundingBoxes())if(distance(eye,box.offset(CompositeData.pos(cell)))<=36)return true;if(VerticalMount.isNative(p.getWorld().getBlockState(root)))for(Box b:p.getWorld().getBlockState(root).getOutlineShape(p.getWorld(),root).getBoundingBoxes())if(distance(eye,b.offset(root))<=36)return true;return false;}
    private static double distance(Vec3d p,Box b){double x=Math.max(Math.max(b.minX-p.x,p.x-b.maxX),0),y=Math.max(Math.max(b.minY-p.y,p.y-b.maxY),0),z=Math.max(Math.max(b.minZ-p.z,p.z-b.maxZ),0);return x*x+y*y+z*z;}
    private static double offset(ServerPlayerEntity p,MechanismLinks.TargetRef t){if(t.kind()==MechanismLinks.Kind.RP&&p.getServerWorld().getEntity(t.instance()) instanceof RpObjectEntity rp)return rp.verticalOffset();return VerticalMount.offset(p.getWorld(),BlockPos.fromLong(t.root()));}
    private static boolean setOffset(ServerPlayerEntity p,MechanismLinks.TargetRef t,double value){if(!Double.isFinite(value))return false;if(t.kind()==MechanismLinks.Kind.RP&&p.getServerWorld().getEntity(t.instance()) instanceof RpObjectEntity rp)return rp.setVerticalOffset(value,p);return VerticalMount.setOffset(p.getServerWorld(),BlockPos.fromLong(t.root()),value,p);}
    private static void objectForm(ServerPlayerEntity p,Session s,JsonObject q){if(!validTarget(p,s)){s.message="Выбранный экземпляр недоступен или вне досягаемости.";return;}String field=text(q,"field",40);boolean done=false;
        switch(field){case "offset" -> done=setOffset(p,s.target,q.get("value").getAsDouble());case "reset_height" -> done=setOffset(p,s.target,0);case "manual" -> done=ObjectPolicies.setManual(p,s.target,q.get("value").getAsBoolean());
            case "dogs" -> {Entity entity=p.getServerWorld().getEntity(s.target.instance());if(entity instanceof RpObjectEntity rp&&rp.supportsDogVisibility()){rp.setDogsVisible(q.get("value").getAsBoolean());done=true;}}
            case "mount" -> {BlockPos root=BlockPos.fromLong(s.target.root());BlockState state=p.getWorld().getBlockState(root);var owner=VerticalMount.owner(p.getWorld(),root);if(owner!=null&&state.contains(ThinWindowRootBlock.MOUNT)){BlockState next=state.with(ThinWindowRootBlock.MOUNT,ThinWindowRootBlock.Mount.valueOf(text(q,"value",20)));done=CompositeRuntime.transition(p.getServerWorld(),owner,next,p).outcome()==TransactionCore.Outcome.COMMITTED;}}
            default -> throw new IllegalArgumentException("object field");}
        s.message=done?"Настройка экземпляра применена.":"Настройка не поддерживается или отклонена сервером.";
    }
    private static void lampForm(ServerPlayerEntity p,Session s,JsonObject q){String line=text(q,"line",64),name=text(q,"name",64);boolean both=q.has("both")&&q.get("both").getAsBoolean();LampEditor.Action action=LampEditor.Action.valueOf(text(q,"action",30));UUID source=null,destination=null;
        if(q.has("destination"))destination=UUID.fromString(text(q,"destination",40));if(q.has("source"))source=UUID.fromString(text(q,"source",40));else if((action==LampEditor.Action.RENAME||action==LampEditor.Action.REGISTER)&&validTarget(p,s)&&s.target.kind()==MechanismLinks.Kind.RP)source=s.target.instance();
        var result=LampEditor.edit(p,new LampEditor.Request(action,source,destination,line,name,both,q.has("confirmed")&&q.get("confirmed").getAsBoolean()));s.message=result.reason();if(result.success()){p.getMainHandStack().getOrCreateNbt().putString("BuilderLampLine",line);p.getMainHandStack().getOrCreateNbt().putBoolean("BuilderLampOneWay",!both);}
    }
    private static void diagnostics(ServerPlayerEntity p,Session s,JsonObject q){if(!p.hasPermissionLevel(2)){s.message="Диагностика доступна оператору уровня 2.";return;}String action=text(q,"action",20),note=text(q,"note",512);switch(action){case "snapshot" -> {if(validTarget(p,s))snapshot(p,s.target,note);else s.message="Для снимка выберите доступный объект.";}
        case "start" -> {DwDiagnostics.Filter filter=DwDiagnostics.Filter.all(p.getServerWorld());if(q.has("selected")&&q.get("selected").getAsBoolean()&&validTarget(p,s))filter=new DwDiagnostics.Filter("object","",s.target.instance().toString(),s.target.dimension(),BlockPos.fromLong(s.target.root()),0);DwDiagnostics.start(p.getServerWorld(),60,filter);s.message="Запись запущена на 60 секунд.";}
        case "stop" -> {DwDiagnostics.stop(p.getServer(),"BUILDER_MENU_STOP");s.message="Запись остановлена.";}case "mark" -> DwDiagnostics.mark(p.getServerWorld(),note);case "export" -> DwDiagnostics.export(p.getServer()).thenAccept(path->p.getServer().execute(()->notice(p,path==null?"Не удалось сохранить отчёт; мир продолжает работать.":"Отчёт: "+path)));case "status" -> s.message="Статус диагностики обновлён.";default -> throw new IllegalArgumentException("diagnostics");}}
    private static void snapshot(ServerPlayerEntity p,MechanismLinks.TargetRef t,String note){if(t.kind()==MechanismLinks.Kind.RP&&p.getServerWorld().getEntity(t.instance()) instanceof RpObjectEntity rp)DwDiagnostics.snapshot(p.getServerWorld(),p,rp,Map.of("note",note));else DwDiagnostics.snapshot(p.getServerWorld(),p,BlockPos.fromLong(t.root()),Map.of("note",note));}
    private record Ray(MechanismLinks.TargetRef ref,double distance){}
    public static List<MechanismLinks.TargetRef> candidates(ServerPlayerEntity player){ServerWorld world=player.getServerWorld();Vec3d eye=player.getEyePos(),end=eye.add(player.getRotationVec(1).multiply(6));List<Ray> hits=new ArrayList<>();
        for(RpObjectEntity rp:dev.dreamwalker.bloodbornerp.object.RpObjectIndex.in(world,new Box(eye,end).expand(1)))if(!rp.isRemoved())for(Box box:rp.selectionBoxes()){var point=box.raycast(eye,end);if(point.isPresent()){hits.add(new Ray(MechanismLinks.TargetRef.rp(rp),point.get().squaredDistanceTo(eye)));break;}}
        Set<dev.dreamwalker.bloodbornedw.runtime.ObjectInstance.Owner> seen=new HashSet<>();for(var cell:CompositeLedger.get(world).cells()){BlockPos pos=CompositeData.pos(cell);if(!world.isChunkLoaded(pos)||pos.getSquaredDistance(BlockPos.ofFloored(eye))>100)continue;for(var c:CompositeLedger.get(world).at(cell)){var hit=CompositeRuntime.shape(c.shape().selection()).raycast(eye,end,pos);if(hit!=null&&seen.add(c.owner()))hits.add(new Ray(new MechanismLinks.TargetRef(MechanismLinks.Kind.ARCHITECTURE,world.getRegistryKey().getValue().toString(),c.owner().instanceId(),CompositeData.pos(c.owner().root()).asLong(),c.owner().registryId()),hit.getPos().squaredDistanceTo(eye)));}}
        HitResult nativeHit=player.raycast(6,1,false);if(nativeHit instanceof BlockHitResult b&&nativeHit.getType()==HitResult.Type.BLOCK){BlockPos pos=b.getBlockPos(),root=SourceLadderRuntime.resolveRoot(world,pos);if(root!=null)pos=root;var owner=VerticalMount.owner(world,pos);if(owner!=null&&seen.add(owner))hits.add(new Ray(new MechanismLinks.TargetRef(MechanismLinks.Kind.ARCHITECTURE,world.getRegistryKey().getValue().toString(),owner.instanceId(),pos.asLong(),owner.registryId()),b.getPos().squaredDistanceTo(eye)));}
        hits.sort(Comparator.comparingDouble(Ray::distance));return hits.stream().map(Ray::ref).distinct().limit(32).toList();
    }
    private static Map<String,Object> targetView(ServerPlayerEntity p,MechanismLinks.TargetRef t){Map<String,Object> out=new LinkedHashMap<>();Identifier registry=new Identifier(t.kind()==MechanismLinks.Kind.RP?"bloodborne_rp:"+t.registryId():t.registryId());var entry=t.kind()==MechanismLinks.Kind.ARCHITECTURE?DebugCatalogue.entry(p.getServerWorld().getBlockState(BlockPos.fromLong(t.root()))):DebugCatalogue.entry(registry);out.put("key",t.key());out.put("name",entry==null?t.registryId():entry.name());out.put("id",entry==null?"?????":entry.temporaryId());out.put("kind",t.kind()==MechanismLinks.Kind.RP?"RP-объект":"Блок");out.put("instance",t.instance().toString());out.put("registry",registry.toString());out.put("position",BlockPos.fromLong(t.root()).toShortString());out.put("dimension",t.dimension());out.put("offset",offset(p,t));var status=MechanismLinks.inspect(p.getServer(),t);out.put("openable",status.availability()==MechanismLinks.Availability.LOADED&&!status.pulseOnly());out.put("pulse",status.pulseOnly());out.put("leversOnly",ObjectPolicies.leversOnly(p.getServer(),t));out.put("pending",MechanismLinks.pending(p.getServer(),t));out.put("rotationStep",90);out.put("profile",false);out.put("mount",false);out.put("dogs",false);out.put("pose",Boolean.TRUE.equals(out.get("openable")));
        if(t.kind()==MechanismLinks.Kind.RP&&p.getServerWorld().getEntity(t.instance()) instanceof RpObjectEntity rp){out.put("rotationStep",45);out.put("dogs",rp.supportsDogVisibility());out.put("yaw",rp.getYaw());out.put("lamp",rp.assetId().equals("hunterlamp"));out.put("lever",rp.isMechanism());out.put("open",rp.isOpen());out.put("dogsVisible",rp.dogsVisible());}
        else{BlockState state=p.getWorld().getBlockState(BlockPos.fromLong(t.root()));out.put("rotationStep",state.getBlock() instanceof ThinWindowRootBlock?90:45);out.put("profile",state.contains(CompositeRootBlock.PROFILE)||state.getBlock() instanceof PrototypeLadderBlock||state.getBlock() instanceof PrototypeWallBlock);out.put("mount",state.contains(ThinWindowRootBlock.MOUNT));if(state.contains(ThinWindowRootBlock.MOUNT))out.put("mountValue",state.get(ThinWindowRootBlock.MOUNT).name());if(state.getBlock() instanceof CompositeRootBlock b)out.put("pose",b.spec.openable);if(state.contains(CompositeRootBlock.OPEN))out.put("open",state.get(CompositeRootBlock.OPEN));}
        if(p.hasPermissionLevel(4)&&Boolean.TRUE.equals(out.get("openable"))){out.put("afterOpen",ObjectPolicies.commands(p.getServer(),t,true));out.put("afterClose",ObjectPolicies.commands(p.getServer(),t,false));}return out;
    }
    private static void send(ServerPlayerEntity p,Session s,boolean open){if(!ServerPlayNetworking.canSend(p,VIEW))return;
        s.candidates=s.candidates.stream().filter(t->near(p,t)).map(t->currentRef(p,t)).toList();if(s.target!=null&&near(p,s.target))s.target=currentRef(p,s.target);Map<String,Object> view=new LinkedHashMap<>();view.put("openMenu",open);view.put("editable",BuildPermissions.canEdit(p));view.put("admin",p.hasPermissionLevel(4));view.put("operator",p.hasPermissionLevel(2));view.put("action",BuildingTool.action(p.getMainHandStack()).name());view.put("actionLabel",BuildingTool.action(p.getMainHandStack()).label);view.put("step",step(p.getMainHandStack()));view.put("pinned",s.pinned);view.put("message",s.message);if(s.target!=null&&near(p,s.target))view.put("target",targetView(p,s.target));view.put("candidates",s.candidates.stream().limit(32).map(t->targetView(p,t)).toList());var related=MechanismRules.list(p.getServer()).stream().filter(r->s.editable.contains(r.id)||s.target!=null&&(r.sources.containsKey(s.target.instance())||r.targets.containsKey(s.target.key()))).toList();int rulePages=Math.max(1,(related.size()+63)/64);s.rulePage=Math.min(s.rulePage,rulePages-1);var visible=related.stream().skip(s.rulePage*64L).limit(64).toList();view.put("rulePage",s.rulePage);view.put("rulePages",rulePages);view.put("ruleTotal",related.size());s.editable.removeIf(id->MechanismRules.rule(p.getServer(),id)==null);visible.forEach(r->{if(s.editable.size()<64)s.editable.add(r.id);});while(s.editable.size()>64)s.editable.remove(s.editable.iterator().next());view.put("rules",visible.stream().map(r->Map.of("id",r.id.toString(),"order",r.order,"name",r.name,"condition",r.condition.name(),"effect",r.effect.name(),"incomplete",r.incomplete)).toList());if(ruleAllowed(p,s))view.put("rule",MechanismRules.view(p.getServer(),MechanismRules.rule(p.getServer(),s.rule),s.affectedPage));view.put("lamps",LampEditor.view(p,null,s.lampPage));if(s.target!=null&&s.target.kind()==MechanismLinks.Kind.RP&&s.target.registryId().equals("hunterlamp"))view.put("currentLamp",LampEditor.view(p,s.target.instance()));view.put("lampLine",p.getMainHandStack().getOrCreateNbt().getString("BuilderLampLine"));view.put("lampBoth",!p.getMainHandStack().getOrCreateNbt().getBoolean("BuilderLampOneWay"));view.put("diagnostics",DwDiagnostics.status(p.getServer()));String json=JSON.toJson(view);if(json.length()>MAX_VIEW){notice(p,"Список слишком велик; выберите отдельное правило.");return;}var buf=PacketByteBufs.create();buf.writeString(json,MAX_VIEW);DwDiagnostics.network("server","send",VIEW.toString(),buf.readableBytes());ServerPlayNetworking.send(p,VIEW,buf);}
    private static MechanismLinks.TargetRef currentRef(ServerPlayerEntity p,MechanismLinks.TargetRef t){if(t.kind()==MechanismLinks.Kind.RP&&p.getServerWorld().getEntity(t.instance()) instanceof RpObjectEntity rp)return MechanismLinks.TargetRef.rp(rp);return t;}
    private static String text(JsonObject q,String key,int limit){String value=q.has(key)?q.get(key).getAsString():"";if(value.length()>limit)throw new IllegalArgumentException(key);return value;}
    private static void notice(ServerPlayerEntity p,String text){if(text!=null&&!text.isBlank())p.sendMessage(Text.literal(text),true);}
}
