package dev.dreamwalker.bloodbornedw.tool;

import com.google.gson.*;
import dev.dreamwalker.bloodbornedw.architecture.BuildingTool;
import java.util.*;
import java.util.function.*;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.*;
import net.minecraft.client.gui.tooltip.Tooltip;
import net.minecraft.text.Text;

/** Forms preserve local drafts across tabs, resizes and server refreshes. */
public final class BuilderScreen extends Screen {
    private static final String[] TABS={"Объект","Связи","Телепорты","События","Диагностика","Управление"};
    private JsonObject view;private int tab,page,rowsPerPage,left,central,right,columnWidth,bodyTop=80,bodyBottom;private boolean details,confirm;
    private final List<Row> rows=new ArrayList<>();private final List<String> rightLines=new ArrayList<>();
    private String draftName="",draftCondition="ANY",draftEffect="TOGGLE",draftLine="",draftLampName="",draftNewLineName="",draftCommand="",draftOffset="0",draftNote="",draftMount="VERTICAL";
    private boolean draftBoth=true,draftManual,commandOpen=true,draftDogs;private int commandIndex=-1;private List<String> commandDraft=new ArrayList<>();
    private final boolean[] dirty=new boolean[6];private final Map<Boolean,List<String>> commandBuffers=new HashMap<>();
    private boolean exitPrompt,saving,serverChanged,confirmConflicts;private String draftTarget="",draftVersion="",draftLampVersion="",pendingId="",pendingOp="";private int savingTab=-1;private JsonObject conflictingView;
    private final Set<Integer> savingTabs=new HashSet<>();
    private final Deque<JsonObject> saveQueue=new ArrayDeque<>();private Runnable afterSave;
    private interface Row {void build(int x,int y,int w);}
    public BuilderScreen(JsonObject view){super(Text.literal("Строительный инструмент"));this.view=view;resetDraft();}
    public void accept(JsonObject next){
        JsonObject previousTarget=target().deepCopy(),previousRule=rule().deepCopy();boolean same=string(previousTarget,"instance","").equals(string(object(next,"target"),"instance",""));String previousVersion=draftVersion;view=next;
        boolean acknowledgement=pendingId.equals(string(next,"requestId",""))&&!pendingId.isBlank();
        if(acknowledgement){String message=string(next,"message","");boolean success=bool(next,"accepted");if(success&&pendingOp.equals("lamp")){draftLampVersion=string(view,"lampVersion","");draftLine=string(view,"lampLine",draftLine);}pendingId="";pendingOp="";
            if(saving&&success){draftVersion=string(target(),"version","");draftLampVersion=string(view,"lampVersion","");if(!saveQueue.isEmpty()){sendNextSave();return;}for(int saved:savingTabs)dirty[saved]=false;savingTabs.clear();saving=false;resetCleanDrafts();if(afterSave!=null){Runnable done=afterSave;afterSave=null;done.run();return;}}
            else if(saving){saveQueue.clear();saving=false;afterSave=null;serverChanged=message.startsWith("Данные изменились");}
        }
        if(!same){if(hasDirty()){conflictingView=next.deepCopy();view.add("target",previousTarget);view.add("rule",previousRule);serverChanged=true;return;}resetDraft();}
        else if(hasDirty()){if(!previousVersion.isBlank()&&!previousVersion.equals(string(target(),"version",previousVersion))&&!acknowledgement)serverChanged=true;}
        else resetDraft();
        // A periodic server refresh must not destroy a focused editor between
        // the focus click and the first character (diagnostic notes are not drafts).
        // Explicit acknowledgements/context changes still rebuild the form.
        if((!hasDirty()&&!textFieldFocused())||acknowledgement||!same)clearAndInit();
    }
    private boolean textFieldFocused(){return children().stream().anyMatch(element->element instanceof TextFieldWidget field&&field.isFocused());}
    public JsonObject currentView(){return view.deepCopy();}
    @Override public boolean shouldPause(){return false;}
    private JsonObject target(){return object(view,"target");}
    private JsonObject rule(){return object(view,"rule");}
    private void resetDraft(){Arrays.fill(dirty,false);serverChanged=false;draftTarget=string(target(),"instance","");draftVersion=string(target(),"version","");draftLampVersion=string(view,"lampVersion","");commandBuffers.clear();resetCleanDrafts();}
    private void resetCleanDrafts(){JsonObject t=target(),r=rule();if(!dirty[0]){draftOffset=string(t,"offset","0");draftManual=bool(t,"leversOnly");draftDogs=bool(t,"dogsVisible");draftMount=string(t,"mountValue","VERTICAL");}if(!dirty[1]){draftName=string(r,"name","");draftCondition=string(r,"condition","ANY");draftEffect=string(r,"effect","TOGGLE");}if(!dirty[2]){draftLine=string(view,"lampLine","");if(draftLine.isBlank())draftLine="Охотничья линия";draftBoth=!view.has("lampBoth")||bool(view,"lampBoth");draftLampName=string(object(object(view,"currentLamp"),"node"),"name","");}if(!dirty[3]){commandBuffers.clear();loadCommands();}}
    private void loadCommands(){commandDraft=new ArrayList<>(commandBuffers.getOrDefault(commandOpen,List.of()));if(!commandBuffers.containsKey(commandOpen))for(JsonElement e:array(target(),commandOpen?"afterOpen":"afterClose"))commandDraft.add(e.getAsString());commandIndex=-1;draftCommand="";}
    private boolean hasDirty(){for(boolean value:dirty)if(value)return true;return bool(rule(),"draft");}
    @Override protected void init(){rows.clear();rightLines.clear();bodyBottom=height-48;left=8;central=8;boolean wide=width>=650;right=wide?(int)(width*.68):width-8;columnWidth=Math.max(100,(wide?right-10:width-8)-central);int tabColumns=width>=480?6:3,tabWidth=(width-16)/tabColumns;bodyTop=76+24*((TABS.length+tabColumns-1)/tabColumns);rowsPerPage=Math.max(1,(bodyBottom-bodyTop)/25);
        for(int i=0;i<TABS.length;i++){final int n=i;var b=button(TABS[i],left+(i%tabColumns)*tabWidth,76+(i/tabColumns)*24,tabWidth-3,()->{tab=n;page=0;confirm=false;clearAndInit();});b.active=tab!=i&&!saving;}
        button(details?"Простой":"Подробности",width-166,6,78,()->{details=!details;clearAndInit();});button("Закрыть",width-84,6,76,this::close);
        switch(tab){case 0->objectTab();case 1->rulesTab();case 2->lampsTab();case 3->eventsTab();case 4->diagnosticsTab();case 5->controlsTab();}
        page=Math.max(0,Math.min(page,Math.max(0,(rows.size()-1)/rowsPerPage)));int start=page*rowsPerPage,end=Math.min(rows.size(),start+rowsPerPage);int y=bodyTop;for(Row r:rows.subList(start,end)){r.build(central,y,columnWidth);y+=25;}
        if(exitPrompt){int part=columnWidth/3;button("Сохранить",central,height-40,part-3,()->saveAll());button("Не сохранять",central+part,height-40,part-3,()->{discardAll();Runnable done=afterSave;afterSave=null;exitPrompt=false;if(done!=null)done.run();else super.close();});button("Остаться",central+2*part,height-40,part-3,()->{exitPrompt=false;afterSave=null;clearAndInit();});}
        else if(tab<4){button(saving?"Ожидание сервера…":"Сохранить",central,height-40,columnWidth/2-3,()->saveTab(tab));button("Отмена формы",central+columnWidth/2+3,height-40,columnWidth/2-3,()->discardTab(tab));}
        if(wide)rightInfo();
    }
    private ButtonWidget button(String label,int x,int y,int w,Runnable action){ButtonWidget b=addDrawableChild(ButtonWidget.builder(Text.literal(textRenderer.trimToWidth(label,Math.max(15,w-12))),widget->action.run()).dimensions(x,y,w,20).tooltip(Tooltip.of(Text.literal(label))).build());b.active=!saving;return b;}
    private void line(String text){rows.add((x,y,w)->addDrawable(new net.minecraft.client.gui.Drawable(){public void render(DrawContext c,int mx,int my,float d){c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth(text,w-6)),x+3,y+6,0xD6C8AF);}}));}
    private void row(String label,Runnable action){rows.add((x,y,w)->button(label,x,y,w,action));}
    private void disabled(String label,String reason){rows.add((x,y,w)->{ButtonWidget b=button(label,x,y,w,()->{});b.active=false;b.setTooltip(Tooltip.of(Text.literal(reason)));});}
    private void pair(String a,Runnable aa,String b,Runnable bb){rows.add((x,y,w)->{button(a,x,y,w/2-2,aa);button(b,x+w/2+2,y,w/2-2,bb);});}
    private void field(String value,int maximum,Consumer<String> changed){rows.add((x,y,w)->{TextFieldWidget f=new TextFieldWidget(textRenderer,x,y,w,20,Text.literal("Поле ввода"));f.setMaxLength(maximum);f.setText(value);f.setChangedListener(v->{changed.accept(v);if(tab<4)dirty[tab]=true;});f.setEditable(!saving);addDrawableChild(f);});}
    private void mode(BuildingTool.Action action,boolean supported,String reason){String active=string(view,"action","");if(active.equals(action.name())&&Set.of(BuildingTool.Action.RULE_SOURCE,BuildingTool.Action.RULE_TARGET,BuildingTool.Action.LAMP_SOURCE,BuildingTool.Action.LAMP_TARGET).contains(action))row("Выбирать в мире: "+action.label,()->BuilderClient.selectInWorld(this));else if(active.equals(action.name()))disabled("● "+action.label,"Текущее действие для одного ЛКМ");else if(!supported)disabled(action.label,reason);else row(action.label,()->{JsonObject q=BuilderClient.request("mode");q.addProperty("action",action.name());if(action==BuildingTool.Action.LAMP_TARGET){q.addProperty("line",draftLine);q.addProperty("both",draftBoth);}BuilderClient.send(q);if(Set.of(BuildingTool.Action.RULE_SOURCE,BuildingTool.Action.RULE_TARGET,BuildingTool.Action.LAMP_SOURCE,BuildingTool.Action.LAMP_TARGET).contains(action))BuilderClient.selectInWorld(this);});}
    private void send(String op,Consumer<JsonObject> values){if(saving||!pendingId.isBlank())return;JsonObject q=BuilderClient.request(op);values.accept(q);if(op.equals("lamp"))q.addProperty("expectedLampVersion",draftLampVersion);if(Set.of("object","commands").contains(op)){q.addProperty("expectedTarget",draftTarget);q.addProperty("expectedVersion",draftVersion);}pendingId=string(q,"requestId","");pendingOp=op;BuilderClient.send(q);}
    private void object(String field,JsonElement value){send("object",q->{q.addProperty("field",field);q.add("value",value);});}
    private void enqueue(String op,int form,Consumer<JsonObject> values){JsonObject q=BuilderClient.request(op);values.accept(q);q.addProperty("draftTab",form);saveQueue.addLast(q);savingTabs.add(form);}
    private void enqueueObject(String field,JsonElement value){enqueue("object",0,q->{q.addProperty("field",field);q.add("value",value);});}
    private void queueTab(int form){savingTabs.add(form);JsonObject t=target();switch(form){
        case 0->{double value=Double.parseDouble(draftOffset);if(value!=Double.parseDouble(string(t,"offset","0")))enqueueObject("offset",new JsonPrimitive(value));if(bool(t,"mount")&&!draftMount.equals(string(t,"mountValue","VERTICAL")))enqueueObject("mount",new JsonPrimitive(draftMount));if(bool(t,"dogs")&&draftDogs!=bool(t,"dogsVisible"))enqueueObject("dogs",new JsonPrimitive(draftDogs));if((bool(t,"openable")||bool(t,"pulse"))&&draftManual!=bool(t,"leversOnly"))enqueueObject("manual",new JsonPrimitive(draftManual));}
        case 1->{if(rule().size()>0)enqueue("rule_apply",1,q->{q.addProperty("name",draftName.isBlank()?string(rule(),"name","Новое правило"):draftName);q.addProperty("condition",draftCondition);q.addProperty("effect",draftEffect);q.addProperty("confirmConflicts",confirmConflicts);});}
        case 2->{if(bool(t,"lamp")&&!draftLampName.isBlank())enqueue("lamp",2,q->{q.addProperty("action","RENAME");q.addProperty("line",draftLine);q.addProperty("name",draftLampName);q.addProperty("both",draftBoth);});enqueue("lamp_parameters",2,q->{q.addProperty("line",draftLine);q.addProperty("both",draftBoth);});}
        case 3->{if(!draftCommand.isBlank()){if(commandIndex>=0)commandDraft.set(commandIndex,draftCommand);else if(commandDraft.size()<32)commandDraft.add(draftCommand);draftCommand="";commandIndex=-1;}commandBuffers.put(commandOpen,new ArrayList<>(commandDraft));for(boolean phase:new boolean[]{true,false})if(commandBuffers.containsKey(phase)){List<String> commands=List.copyOf(commandBuffers.get(phase));enqueue("commands",3,q->{q.addProperty("open",phase);JsonArray a=new JsonArray();commands.forEach(a::add);q.add("commands",a);});}}
    }}
    private void saveTab(int form){if(saving||!pendingId.isBlank())return;saveQueue.clear();savingTabs.clear();try{queueTab(form);}catch(NumberFormatException invalid){serverChanged=true;clearAndInit();return;}startSaving();}
    private void saveAll(){if(saving)return;saveQueue.clear();savingTabs.clear();try{for(int i=0;i<4;i++)if(dirty[i]||i==1&&bool(rule(),"draft"))queueTab(i);}catch(NumberFormatException invalid){serverChanged=true;clearAndInit();return;}exitPrompt=false;startSaving();}
    private void startSaving(){if(saveQueue.isEmpty()){for(int form:savingTabs)dirty[form]=false;savingTabs.clear();resetCleanDrafts();if(afterSave!=null){Runnable done=afterSave;afterSave=null;done.run();}else clearAndInit();return;}saving=true;sendNextSave();clearAndInit();}
    private void sendNextSave(){JsonObject q=saveQueue.removeFirst();savingTab=q.remove("draftTab").getAsInt();if(string(q,"op","").equals("lamp"))q.addProperty("expectedLampVersion",draftLampVersion);if(Set.of("object","commands").contains(string(q,"op",""))){q.addProperty("expectedTarget",draftTarget);q.addProperty("expectedVersion",draftVersion);}pendingId=string(q,"requestId","");pendingOp=string(q,"op","");BuilderClient.send(q);}
    private void discardAll(){if(bool(rule(),"draft")){JsonObject q=BuilderClient.request("rule_discard");BuilderClient.send(q);view.remove("rule");}if(conflictingView!=null){view=conflictingView;conflictingView=null;}resetDraft();saveQueue.clear();savingTabs.clear();pendingId="";saving=false;}
    private void discardTab(int form){if(form==1){send("rule_discard",q->{});view.remove("rule");}dirty[form]=false;if(form==3)commandBuffers.clear();resetCleanDrafts();clearAndInit();}
    private void chooseContext(Runnable change){if(hasDirty()){afterSave=change;exitPrompt=true;clearAndInit();}else change.run();}
    @Override public void close(){if(saving)return;if(hasDirty()){afterSave=()->super.close();exitPrompt=true;clearAndInit();}else super.close();}
    private void controlsTab(){for(String info:BuilderClient.controls())line(info);row("Переназначить комбинации…",()->client.setScreen(new BuilderControlsScreen(this)));line("Общий ключ применяется к 90009 только в игровом контексте.");for(String conflict:BuilderClient.conflicts())line("Общий ввод: "+conflict);}
    private void objectTab(){JsonObject t=target();boolean found=t.size()>0&&bool(t,"available"),edit=bool(view,"editable")&&found;
        mode(BuildingTool.Action.SELECT,true,"");for(JsonElement e:array(view,"candidates")){JsonObject candidate=e.getAsJsonObject();row("Выбрать: "+label(candidate),()->chooseContext(()->send("select",q->q.addProperty("key",string(candidate,"key","")))));}
        mode(BuildingTool.Action.ROTATE,edit,"Выберите поддерживающий поворот объект в досягаемости.");line("Шаг поворота: "+string(t,"rotationStep","—")+"°. Самостоятельный тип сохраняется.");
        mode(BuildingTool.Action.UP,edit,"Сначала выберите объект мода.");mode(BuildingTool.Action.DOWN,edit,"Сначала выберите объект мода.");
        line("Шаг высоты: "+string(view,"step","0.125")+" блока");rows.add((x,y,w)->{double[] steps={.0625,.125,.25,1};String[] names={"1/16","1/8","1/4","1"};for(int i=0;i<4;i++){double step=steps[i];var b=button(names[i],x+i*w/4,y,w/4-2,()->send("step",q->q.addProperty("value",step)));b.active=Math.abs(Double.parseDouble(string(view,"step",".125"))-step)>.00001;}});
        line("Точное монтажное смещение по Y (блоки)");field(draftOffset,32,v->draftOffset=v);pair("Применить высоту",()->saveTab(0),"Отмена",()->{draftOffset=string(t,"offset","0");clearAndInit();});row("Сбросить высоту",()->{draftOffset="0";dirty[0]=true;clearAndInit();});
        mode(BuildingTool.Action.PROFILE,edit&&bool(t,"profile"),"У этого объекта нет переключения BASE/ALT.");mode(BuildingTool.Action.POSE,edit&&bool(t,"pose"),"Нет устойчивого состояния панелей / открытия.");
        if(bool(t,"mount")){row("Установка: "+mountName(draftMount),()->{List<String> mounts=List.of("VERTICAL","FLOOR","CEILING");draftMount=mounts.get((mounts.indexOf(draftMount)+1)%3);dirty[0]=true;clearAndInit();});pair("Применить установку",()->saveTab(0),"Отмена",()->{draftMount=string(t,"mountValue","VERTICAL");clearAndInit();});}else disabled("Установка остекления","Этот тип не поддерживает три монтажные плоскости.");
        if(bool(t,"dogs")){row("Собаки: "+(draftDogs?"видимы":"скрыты"),()->{draftDogs=!draftDogs;dirty[0]=true;clearAndInit();});pair("Применить содержимое",()->saveTab(0),"Отмена",()->{draftDogs=bool(t,"dogsVisible");clearAndInit();});}else disabled("Содержимое: собаки","Для этого типа нет отдельного содержимого.");
        if(bool(t,"openable")||bool(t,"pulse")){row("Управление: "+(draftManual?"Только рычагами":"Рукой и рычагами"),()->{draftManual=!draftManual;dirty[0]=true;clearAndInit();});pair("Применить управление",()->saveTab(0),"Отмена",()->{draftManual=bool(t,"leversOnly");draftDogs=bool(t,"dogsVisible");draftMount=string(t,"mountValue","VERTICAL");clearAndInit();});}else disabled("Ручное управление","Статичный объект не получает выдуманное открытие.");
        row("Отменить рабочий выбор",()->chooseContext(()->send("cancel_selection",q->{})));
    }
    private void rulesTab(){JsonObject r=rule();if(bool(view,"operator"))row(bool(view,"globalRules")?"Показаны все правила сервера":"Правила выбранного экземпляра",()->chooseContext(()->send("rules_scope",q->q.addProperty("global",!bool(view,"globalRules")))));line("1. Источники → 2. Цели → 3. Завершить");field(draftName,80,v->draftName=v);row("Создать правило (Любой, открывать/закрывать)",()->{String name=draftName;chooseContext(()->send("rule_create",q->q.addProperty("name",name)));});
        for(JsonElement e:array(view,"rules")){JsonObject item=e.getAsJsonObject();row("№"+string(item,"order","")+" · "+string(item,"name","")+" · "+condition(string(item,"condition","ANY")),()->chooseContext(()->send("rule_select",q->q.addProperty("id",string(item,"id","")))));}
        int rulePage=Integer.parseInt(string(view,"rulePage","0")),rulePages=Integer.parseInt(string(view,"rulePages","1"));if(rulePages>1){line("Правила: страница "+(rulePage+1)+" / "+rulePages);pair("Предыдущие правила",()->send("rule_page",q->q.addProperty("page",Math.max(0,rulePage-1))),"Следующие правила",()->send("rule_page",q->q.addProperty("page",Math.min(rulePages-1,rulePage+1))));}
        if(r.size()==0){line("Создайте правило или выберите входящую/исходящую связь.");return;}
        line((bool(r,"draft")?"Черновик":"Сохранённое правило")+" · "+string(r,"name",""));line(bool(r,"incomplete")?"Неполное: исправьте состав после удаления участника.":"Активированы "+string(r,"active","0")+" из "+string(r,"total","0"));
        for(JsonElement conflict:array(r,"conflicts"))line("Конфликт: "+conflict.getAsString());if(array(r,"conflicts").size()>0)row("Подтверждение порядка: "+(confirmConflicts?"да":"нет"),()->{confirmConflicts=!confirmConflicts;dirty[1]=true;clearAndInit();});mode(BuildingTool.Action.RULE_SOURCE,true,"");mode(BuildingTool.Action.RULE_TARGET,true,"");line("Выбранный режим действует по ЛКМ после закрытия меню.");
        row("Условие: "+condition(draftCondition),()->{draftCondition=draftCondition.equals("ANY")?"ALL":"ANY";dirty[1]=true;clearAndInit();});row("Действие: "+effect(draftEffect),()->{List<String> choices=List.of("TOGGLE","OPEN","CLOSE","PULSE");draftEffect=choices.get((choices.indexOf(draftEffect)+1)%choices.size());dirty[1]=true;clearAndInit();});pair("Применить правило",()->saveTab(1),"Отмена формы",()->discardTab(1));
        for(boolean source:new boolean[]{true,false}){line(source?"Источники":"Цели (порядок правил определяет итог)");for(JsonElement e:array(r,source?"sources":"targets")){JsonObject item=e.getAsJsonObject();String text=string(item,"name","Объект")+" ["+string(item,"type","?????")+"] · "+string(item,"position","")+(!source?" · "+string(item,"supportedAction",""):"")+(source?bool(item,"active")?" · активен":" · выключен":bool(item,"pending")?" · ожидает закрытия / действия":"")+(Long.parseLong(string(item,"conflictingRules","0"))>1?" · несколько правил":"");row(text+" · убрать из черновика",()->{dirty[1]=true;send("rule_remove_member",q->{q.addProperty("key",string(item,"key",""));q.addProperty("source",source);});});}}
        line("Сброс затронет групп «Все»: "+string(r,"affectedResetTotal","0")+" (общие признаки)");for(JsonElement affected:array(r,"affectedResetNames"))line("→ "+affected.getAsString());int affectedPage=Integer.parseInt(string(r,"affectedResetPage","0")),affectedPages=Integer.parseInt(string(r,"affectedResetPages","1"));if(affectedPages>1)pair("Предыдущие затронутые группы",()->send("affected_page",q->q.addProperty("page",Math.max(0,affectedPage-1))),"Следующие затронутые группы",()->send("affected_page",q->q.addProperty("page",Math.min(affectedPages-1,affectedPage+1))));if(confirm){pair("Подтвердить сброс",()->send("rule_reset",q->q.addProperty("confirmed",true)),"Отмена",()->{confirm=false;clearAndInit();});pair("Удалить правило и его связи",()->send("rule_delete",q->q.addProperty("confirmed",true)),"Отмена",()->{confirm=false;clearAndInit();});}else row("Сброс / удаление: показать подтверждение",()->{confirm=true;clearAndInit();});row("Завершить выбор (сохранённые связи остаются)",()->chooseContext(()->send("cancel_selection",q->{})));
    }
    private void lampsTab(){JsonObject lamps=object(view,"lamps"),node=object(lamps,"node");line("1. Исходный фонарь → 2. Назначения → 3. Завершить");line("Источник: "+string(node,"name","не выбран"));mode(BuildingTool.Action.LAMP_SOURCE,bool(view,"operator"),"Настройка сети доступна оператору уровня 2.");
        line("Имя выбранного фонаря");field(draftLampName,64,v->draftLampName=v);row("Применить имя выбранного фонаря",()->saveTab(2));
        line("Именованная линия (явные связи)");field(draftLine,64,v->draftLine=v);for(JsonElement e:array(lamps,"lines")){JsonObject line=e.getAsJsonObject();row("Линия: "+string(line,"name","")+" · связей "+string(line,"connectionCount","0"),()->{draftLine=string(line,"name","");clearAndInit();});}
        pair("Создать линию",()->lamp("CREATE_LINE",null,null,false),"Выбрать линию",()->send("lamp_parameters",q->{q.addProperty("line",draftLine);q.addProperty("both",draftBoth);}));line("Новое имя линии (не имя фонаря)");field(draftNewLineName,64,v->draftNewLineName=v);row("Переименовать линию",()->lamp("RENAME_LINE",null,null,false));row("Направление: "+(draftBoth?"В обе стороны":"Только к назначению"),()->{draftBoth=!draftBoth;dirty[2]=true;clearAndInit();});
        row("Применить параметры назначения",()->send("lamp_parameters",q->{q.addProperty("line",draftLine);q.addProperty("both",draftBoth);}));mode(BuildingTool.Action.LAMP_TARGET,bool(view,"operator"),"Нужны права оператора и исходный фонарь.");line("ЛКМ добавляет назначения, источник сохраняется.");
        line("Маршруты: "+array(lamps,"outgoingNames").toString());for(JsonElement e:array(lamps,"connections")){JsonObject c=e.getAsJsonObject(),a=object(c,"source"),b=object(c,"destination");String current=string(node,"entityUuid","");JsonObject dest=current.equals(string(a,"entityUuid",""))?b:a;String source=current;String target=string(dest,"entityUuid","");line(string(c,"lineName","")+": "+string(a,"name","")+(bool(c,"aToB")&&bool(c,"bToA")?" ↔ ":bool(c,"aToB")?" → ":" ← ")+string(b,"name","")+(bool(c,"reverseOtherLines")?" · обратный путь есть в другой линии":""));pair("Направление → "+string(dest,"name","назначение"),()->{draftLine=string(c,"lineName","");lamp("SET_DIRECTION",source,target,false);},"Разорвать → "+string(dest,"name","назначение"),()->{draftLine=string(c,"lineName","");lamp("UNLINK",source,target,false);});}
        int routePage=Integer.parseInt(string(lamps,"page","0")),routePages=Integer.parseInt(string(lamps,"pageCount","1"));if(routePages>1){line("Маршруты: страница "+(routePage+1)+" / "+routePages);pair("Предыдущие маршруты",()->send("lamp_page",q->q.addProperty("page",Math.max(0,routePage-1))),"Следующие маршруты",()->send("lamp_page",q->q.addProperty("page",Math.min(routePages-1,routePage+1))));}
        if(confirm)pair("Удалить линию «"+draftLine+"»",()->lamp("DELETE_LINE",null,null,true),"Отмена",()->{confirm=false;clearAndInit();});else row("Удалить всю линию…",()->{confirm=true;clearAndInit();});row("Отменить выбор источника",()->chooseContext(()->send("cancel_selection",q->{})));
    }
    private void lamp(String action,String source,String destination,boolean confirmed){send("lamp",q->{q.addProperty("action",action);q.addProperty("line",draftLine);q.addProperty("name",action.equals("RENAME_LINE")?draftNewLineName:draftLampName);q.addProperty("both",draftBoth);q.addProperty("confirmed",confirmed);if(source!=null)q.addProperty("source",source);if(destination!=null)q.addProperty("destination",destination);});}
    private void eventsTab(){if(!bool(view,"admin")){disabled("Редактор команд","Требуются серверные права администратора уровня 4; Creative их не заменяет.");return;}if(!bool(target(),"openable")){disabled("После открытия / закрытия","Выберите объект с настоящими устойчивыми состояниями. Для импульсного или статичного типа эти события отсутствуют.");return;}
        row(commandOpen?"После открытия":"После закрытия",()->{commandBuffers.put(commandOpen,new ArrayList<>(commandDraft));commandOpen=!commandOpen;loadCommands();clearAndInit();});line("Команды сервера по порядку; сохраняются только кнопкой ниже.");for(int i=0;i<commandDraft.size();i++){final int index=i;row((i+1)+". "+commandDraft.get(i),()->{commandIndex=index;draftCommand=commandDraft.get(index);clearAndInit();});}
        field(draftCommand,2048,v->draftCommand=v);pair(commandIndex<0?"Добавить команду":"Изменить выбранную",()->{if(!draftCommand.isBlank()){if(commandIndex<0&&commandDraft.size()<32)commandDraft.add(draftCommand);else if(commandIndex>=0)commandDraft.set(commandIndex,draftCommand);draftCommand="";commandIndex=-1;dirty[3]=true;clearAndInit();}},"Убрать выбранную",()->{if(commandIndex>=0){commandDraft.remove(commandIndex);commandIndex=-1;draftCommand="";dirty[3]=true;clearAndInit();}});
        pair("Переместить выше",()->moveCommand(-1),"Переместить ниже",()->moveCommand(1));pair("Сохранить список команд",()->saveTab(3),"Отмена формы",()->{loadCommands();clearAndInit();});
        line("Подстановки: {id}, {uuid}, {x}, {y}, {z}, {dimension}, {player}");line("Без игрока команда с {player} пропускается. UUID блока не является @e.");line("Пример: execute positioned {x} {y} {z} run playsound minecraft:block.note_block.bell master @a[distance=..16]");
    }
    private void moveCommand(int delta){int next=commandIndex+delta;if(commandIndex>=0&&next>=0&&next<commandDraft.size()){Collections.swap(commandDraft,commandIndex,next);commandIndex=next;dirty[3]=true;clearAndInit();}}
    private void diagnosticsTab(){for(String visual:List.of("selection","collision","links","root"))row(BuilderClient.visualLabel(visual),()->{BuilderClient.toggleVisual(visual);clearAndInit();});line("Осмотр и снимок не меняют объект.");mode(BuildingTool.Action.SELECT,true,"");mode(BuildingTool.Action.DIAGNOSTICS,bool(view,"operator"),"Снимки доступны оператору уровня 2.");line("Пометка к снимку / записи");field(draftNote,512,v->draftNote=v);row("Сохранить снимок выбранного объекта",()->diagnostics("snapshot",true));pair("Запись 60 с: всё",()->diagnostics("start",false),"60 с: выбранный объект",()->diagnostics("start",true));pair("Остановить запись",()->diagnostics("stop",false),"Сохранить пометку",()->diagnostics("mark",false));pair("Обновить статус",()->diagnostics("status",false),"Экспорт ZIP",()->diagnostics("export",false));row("Открыть локальную папку отчётов клиента",BuilderClient::openReportFolder);line("Серверный ZIP находится на сервере; клиентская кнопка его путь не открывает.");JsonObject d=object(view,"diagnostics");line(bool(d,"enabled")?"Идёт запись · осталось "+string(d,"remainingSeconds","?")+" с":"Запись выключена · "+string(d,"stopReason",""));line("Сеанс: "+string(d,"sessionId","NONE"));line("FPS ≠ точная нагрузка блока; CPU рендера ≠ время GPU.");if(details)for(var entry:d.entrySet())line(entry.getKey()+": "+entry.getValue());}
    private void diagnostics(String action,boolean selected){send("diagnostics",q->{q.addProperty("action",action);q.addProperty("note",draftNote);q.addProperty("selected",selected);});}
    private void rightInfo(){JsonObject t=target();rightLines.add("Параметры и выбранный экземпляр");rightLines.add(string(t,"name","Нет объекта под прицелом"));rightLines.add(string(t,"kind","")+" ["+string(t,"id","?????")+"]");rightLines.add("Положение: "+string(t,"position","—"));rightLines.add("Смещение Y: "+string(t,"offset","—"));rightLines.add(bool(view,"pinned")?"Закреплённый выбор":"Объект под прицелом");rightLines.add("Один ЛКМ — одна операция.");rightLines.add("ПКМ открывает меню.");rightLines.add("Разрушение с инструментом отменено.");JsonObject r=rule();if(r.size()>0){rightLines.add("Правило: "+string(r,"name",""));rightLines.add("Активированы "+string(r,"active","0")+" из "+string(r,"total","0"));}if(details){rightLines.add("Registry: "+string(t,"registry","—"));rightLines.add("UUID: "+string(t,"instance","—"));rightLines.add("Измерение: "+string(t,"dimension","—"));} }
    @Override public void render(DrawContext c,int mx,int my,float delta){renderBackground(c);c.fill(4,4,width-4,height-4,0xE018181D);c.drawTextWithShadow(textRenderer,title,10,10,0xDEC395);c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth("Действие: "+string(view,"actionLabel","выбрать"),width-20)),10,27,0xE2D5B6);JsonObject t=target();c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth((bool(view,"pinned")?"Закреплён: ":"Прицел: ")+label(t),width-20)),10,41,0xC5C5C5);c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth(string(view,"message",""),width-20)),10,57,0xE1B272);
        if(width>=650){c.fill(right-5,75,right-4,bodyBottom,0xFF504736);int y=82;for(String line:rightLines)for(var part:textRenderer.wrapLines(Text.literal(line),Math.max(100,width-right-12))){if(y>=bodyBottom-10)break;c.drawTextWithShadow(textRenderer,part,right+2,y,0xD6C8AF);y+=12;} }
        c.drawCenteredTextWithShadow(textRenderer,Text.literal("Страница "+(page+1)+" / "+Math.max(1,(rows.size()+rowsPerPage-1)/rowsPerPage)+" · колесо"+(serverChanged?" · конфликт / неверное значение":saving?" · ждём подтверждения":hasDirty()?" · НЕ СОХРАНЕНО":" · сохранено")),central+columnWidth/2,height-16,0xA4A4A4);super.render(c,mx,my,delta);}
    @Override public boolean mouseScrolled(double x,double y,double amount){if(amount!=0){int next=Math.max(0,Math.min(Math.max(0,(rows.size()-1)/rowsPerPage),page+(amount<0?1:-1)));if(next!=page){page=next;clearAndInit();}return true;}return super.mouseScrolled(x,y,amount);}
    private static JsonObject object(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonObject()?o.getAsJsonObject(k):new JsonObject();}
    private static JsonArray array(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonArray()?o.getAsJsonArray(k):new JsonArray();}
    private static String string(JsonObject o,String k,String fallback){return o.has(k)&&o.get(k).isJsonPrimitive()?o.get(k).getAsString():fallback;}
    private static boolean bool(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonPrimitive()&&o.get(k).getAsBoolean();}
    private static String label(JsonObject o){return o.size()==0?"Нет выбранного объекта":string(o,"name","")+" ["+string(o,"id","?????")+"] · "+string(o,"position","");}
    private static String mountName(String mount){return switch(mount){case "FLOOR"->"Пол";case "CEILING"->"Потолок";default->"Вертикально";};}
    private static String condition(String value){return value.equals("ALL")?"Все":"Любой";}
    private static String effect(String value){return switch(value){case "OPEN"->"Только открывать";case "CLOSE"->"Только закрывать";case "PULSE"->"Одиночная анимация";default->"Открывать и закрывать";};}
}
