package dev.dreamwalker.bloodbornedw.tool;

import com.google.gson.*;
import dev.dreamwalker.bloodbornedw.architecture.BuildingTool;
import java.util.*;
import java.util.function.*;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.*;
import net.minecraft.client.gui.tooltip.Tooltip;
import net.minecraft.text.Text;

/** Drafts stay client-local until Apply. Changing tab or Esc discards unfinished forms. */
public final class BuilderScreen extends Screen {
    private static final String[] TABS={"Объект","Рычаги","Фонари","События","Диагностика"};
    private JsonObject view;private int tab,page,rowsPerPage,left,central,right,columnWidth,bodyTop=80,bodyBottom;private boolean details,confirm;
    private final List<Row> rows=new ArrayList<>();private final List<String> rightLines=new ArrayList<>();
    private String draftName="",draftCondition="ANY",draftEffect="TOGGLE",draftLine="",draftLampName="",draftCommand="",draftOffset="0",draftNote="",draftMount="VERTICAL";
    private boolean draftBoth=true,draftManual,commandOpen=true,draftDogs;private int commandIndex=-1;private List<String> commandDraft=new ArrayList<>();
    private interface Row {void build(int x,int y,int w);}
    public BuilderScreen(JsonObject view){super(Text.literal("Строительный инструмент"));this.view=view;resetDraft();}
    public void accept(JsonObject next){view=next;confirm=false;resetDraft();clearAndInit();}
    public JsonObject currentView(){return view.deepCopy();}
    @Override public boolean shouldPause(){return false;}
    private JsonObject target(){return object(view,"target");}
    private JsonObject rule(){return object(view,"rule");}
    private void resetDraft(){JsonObject t=target(),r=rule();draftOffset=string(t,"offset","0");draftManual=bool(t,"leversOnly");draftDogs=bool(t,"dogsVisible");draftMount=string(t,"mountValue","VERTICAL");draftName=string(r,"name","");draftCondition=string(r,"condition","ANY");draftEffect=string(r,"effect","TOGGLE");draftLine=string(view,"lampLine","");if(draftLine.isBlank())draftLine="Охотничья линия";draftBoth=!view.has("lampBoth")||bool(view,"lampBoth");draftLampName=string(object(view,"currentLamp").has("node")?object(object(view,"currentLamp"),"node"):new JsonObject(),"name","");loadCommands();}
    private void loadCommands(){commandDraft=new ArrayList<>();for(JsonElement e:array(target(),commandOpen?"afterOpen":"afterClose"))commandDraft.add(e.getAsString());commandIndex=-1;draftCommand="";}
    @Override protected void init(){rows.clear();rightLines.clear();bodyBottom=height-48;left=8;central=112;boolean wide=width>=650;right=wide?(int)(width*.68):width-8;columnWidth=Math.max(140,(wide?right-10:width-8)-central);rowsPerPage=Math.max(1,(bodyBottom-bodyTop)/25);
        for(int i=0;i<TABS.length;i++){final int n=i;var b=button(TABS[i],left,bodyTop+i*27,96,()->{tab=n;page=0;confirm=false;resetDraft();clearAndInit();});b.active=tab!=i;}
        button(details?"Простой":"Подробности",left,height-72,96,()->{details=!details;clearAndInit();});button("Закрыть",left,height-44,96,this::close);
        switch(tab){case 0->objectTab();case 1->rulesTab();case 2->lampsTab();case 3->eventsTab();case 4->diagnosticsTab();}
        page=Math.max(0,Math.min(page,Math.max(0,(rows.size()-1)/rowsPerPage)));int start=page*rowsPerPage,end=Math.min(rows.size(),start+rowsPerPage);int y=bodyTop;for(Row r:rows.subList(start,end)){r.build(central,y,columnWidth);y+=25;}
        if(page>0)button("↑",central,height-40,35,()->{page--;clearAndInit();});if(end<rows.size())button("↓",central+columnWidth-35,height-40,35,()->{page++;clearAndInit();});
        if(wide)rightInfo();
    }
    private ButtonWidget button(String label,int x,int y,int w,Runnable action){return addDrawableChild(ButtonWidget.builder(Text.literal(textRenderer.trimToWidth(label,Math.max(15,w-12))),b->action.run()).dimensions(x,y,w,20).tooltip(Tooltip.of(Text.literal(label))).build());}
    private void line(String text){rows.add((x,y,w)->addDrawable(new net.minecraft.client.gui.Drawable(){public void render(DrawContext c,int mx,int my,float d){c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth(text,w-6)),x+3,y+6,0xD6C8AF);}}));}
    private void row(String label,Runnable action){rows.add((x,y,w)->button(label,x,y,w,action));}
    private void disabled(String label,String reason){rows.add((x,y,w)->{ButtonWidget b=button(label,x,y,w,()->{});b.active=false;b.setTooltip(Tooltip.of(Text.literal(reason)));});}
    private void pair(String a,Runnable aa,String b,Runnable bb){rows.add((x,y,w)->{button(a,x,y,w/2-2,aa);button(b,x+w/2+2,y,w/2-2,bb);});}
    private void field(String value,int maximum,Consumer<String> changed){rows.add((x,y,w)->{TextFieldWidget f=new TextFieldWidget(textRenderer,x,y,w,20,Text.literal("Поле ввода"));f.setMaxLength(maximum);f.setText(value);f.setChangedListener(changed);addDrawableChild(f);});}
    private void mode(BuildingTool.Action action,boolean supported,String reason){String active=string(view,"action","");if(active.equals(action.name()))disabled("● "+action.label,"Текущее действие для одного ЛКМ");else if(!supported)disabled(action.label,reason);else row(action.label,()->{JsonObject q=BuilderClient.request("mode");q.addProperty("action",action.name());if(action==BuildingTool.Action.LAMP_TARGET){q.addProperty("line",draftLine);q.addProperty("both",draftBoth);}BuilderClient.send(q);});}
    private void send(String op,Consumer<JsonObject> values){JsonObject q=BuilderClient.request(op);values.accept(q);BuilderClient.send(q);}
    private void object(String field,JsonElement value){send("object",q->{q.addProperty("field",field);q.add("value",value);});}
    private void objectTab(){JsonObject t=target();boolean found=t.size()>0,edit=bool(view,"editable")&&found;
        mode(BuildingTool.Action.SELECT,true,"");for(JsonElement e:array(view,"candidates")){JsonObject candidate=e.getAsJsonObject();row("Выбрать: "+label(candidate),()->send("select",q->q.addProperty("key",string(candidate,"key",""))));}
        mode(BuildingTool.Action.ROTATE,edit,"Выберите поддерживающий поворот объект в досягаемости.");line("Шаг поворота: "+string(t,"rotationStep","—")+"°. Самостоятельный тип сохраняется.");
        mode(BuildingTool.Action.UP,edit,"Сначала выберите объект мода.");mode(BuildingTool.Action.DOWN,edit,"Сначала выберите объект мода.");
        line("Шаг высоты: "+string(view,"step","0.125")+" блока");rows.add((x,y,w)->{double[] steps={.0625,.125,.25,1};String[] names={"1/16","1/8","1/4","1"};for(int i=0;i<4;i++){double step=steps[i];var b=button(names[i],x+i*w/4,y,w/4-2,()->send("step",q->q.addProperty("value",step)));b.active=Math.abs(Double.parseDouble(string(view,"step",".125"))-step)>.00001;}});
        line("Точное монтажное смещение по Y (блоки)");field(draftOffset,32,v->draftOffset=v);pair("Применить высоту",()->{try{object("offset",new JsonPrimitive(Double.parseDouble(draftOffset)));}catch(NumberFormatException invalid){draftOffset=string(t,"offset","0");}},"Отмена",()->{draftOffset=string(t,"offset","0");clearAndInit();});row("Сбросить высоту",()->object("reset_height",new JsonPrimitive(0)));
        mode(BuildingTool.Action.PROFILE,edit&&bool(t,"profile"),"У этого объекта нет переключения BASE/ALT.");mode(BuildingTool.Action.POSE,edit&&bool(t,"pose"),"Нет устойчивого состояния панелей / открытия.");
        if(bool(t,"mount")){row("Установка: "+mountName(draftMount),()->{List<String> mounts=List.of("VERTICAL","FLOOR","CEILING");draftMount=mounts.get((mounts.indexOf(draftMount)+1)%3);clearAndInit();});pair("Применить установку",()->object("mount",new JsonPrimitive(draftMount)),"Отмена",()->{draftMount=string(t,"mountValue","VERTICAL");clearAndInit();});}else disabled("Установка остекления","Этот тип не поддерживает три монтажные плоскости.");
        if(bool(t,"dogs")){row("Собаки: "+(draftDogs?"Показать":"Скрыть"),()->{draftDogs=!draftDogs;clearAndInit();});pair("Применить содержимое",()->object("dogs",new JsonPrimitive(draftDogs)),"Отмена",()->{draftDogs=bool(t,"dogsVisible");clearAndInit();});}else disabled("Содержимое: собаки","Для этого типа нет отдельного содержимого.");
        if(bool(t,"openable")||bool(t,"pulse")){row("Управление: "+(draftManual?"Только рычагами":"Рукой и рычагами"),()->{draftManual=!draftManual;clearAndInit();});pair("Применить управление",()->object("manual",new JsonPrimitive(draftManual)),"Отмена",()->{draftManual=bool(t,"leversOnly");draftDogs=bool(t,"dogsVisible");draftMount=string(t,"mountValue","VERTICAL");clearAndInit();});}else disabled("Ручное управление","Статичный объект не получает выдуманное открытие.");
        row("Отменить рабочий выбор",()->send("cancel_selection",q->{}));
    }
    private void rulesTab(){JsonObject r=rule();line("1. Источники → 2. Цели → 3. Завершить");field(draftName,80,v->draftName=v);row("Создать правило (Любой, открывать/закрывать)",()->send("rule_create",q->q.addProperty("name",draftName)));
        for(JsonElement e:array(view,"rules")){JsonObject item=e.getAsJsonObject();row("№"+string(item,"order","")+" · "+string(item,"name","")+" · "+condition(string(item,"condition","ANY")),()->send("rule_select",q->q.addProperty("id",string(item,"id",""))));}
        int rulePage=Integer.parseInt(string(view,"rulePage","0")),rulePages=Integer.parseInt(string(view,"rulePages","1"));if(rulePages>1){line("Правила: страница "+(rulePage+1)+" / "+rulePages);pair("Предыдущие правила",()->send("rule_page",q->q.addProperty("page",Math.max(0,rulePage-1))),"Следующие правила",()->send("rule_page",q->q.addProperty("page",Math.min(rulePages-1,rulePage+1))));}
        if(r.size()==0){line("Создайте правило или выберите входящую/исходящую связь.");return;}
        line("Правило №"+string(r,"order","")+": "+string(r,"name",""));line(bool(r,"incomplete")?"Неполное: исправьте состав после удаления участника.":"Активированы "+string(r,"active","0")+" из "+string(r,"total","0"));
        mode(BuildingTool.Action.RULE_SOURCE,true,"");mode(BuildingTool.Action.RULE_TARGET,true,"");line("Выбранный режим действует по ЛКМ после закрытия меню.");
        row("Условие: "+condition(draftCondition),()->{draftCondition=draftCondition.equals("ANY")?"ALL":"ANY";clearAndInit();});row("Действие: "+effect(draftEffect),()->{List<String> choices=List.of("TOGGLE","OPEN","CLOSE","PULSE");draftEffect=choices.get((choices.indexOf(draftEffect)+1)%choices.size());clearAndInit();});pair("Применить правило",()->send("rule_apply",q->{q.addProperty("name",draftName);q.addProperty("condition",draftCondition);q.addProperty("effect",draftEffect);}),"Отмена формы",()->{resetDraft();clearAndInit();});
        for(boolean source:new boolean[]{true,false}){line(source?"Источники":"Цели (порядок правил определяет итог)");for(JsonElement e:array(r,source?"sources":"targets")){JsonObject item=e.getAsJsonObject();String text=string(item,"name","Объект")+" ["+string(item,"type","?????")+"] · "+string(item,"position","")+(!source?" · "+string(item,"supportedAction",""):"")+(source?bool(item,"active")?" · активен":" · выключен":bool(item,"pending")?" · ожидает закрытия / действия":"")+(Long.parseLong(string(item,"conflictingRules","0"))>1?" · несколько правил":"");row(text+" · убрать",()->send("rule_remove_member",q->{q.addProperty("key",string(item,"key",""));q.addProperty("source",source);}));}}
        line("Сброс затронет групп «Все»: "+string(r,"affectedResetTotal","0")+" (общие признаки)");for(JsonElement affected:array(r,"affectedResetNames"))line("→ "+affected.getAsString());int affectedPage=Integer.parseInt(string(r,"affectedResetPage","0")),affectedPages=Integer.parseInt(string(r,"affectedResetPages","1"));if(affectedPages>1)pair("Предыдущие затронутые группы",()->send("affected_page",q->q.addProperty("page",Math.max(0,affectedPage-1))),"Следующие затронутые группы",()->send("affected_page",q->q.addProperty("page",Math.min(affectedPages-1,affectedPage+1))));if(confirm){pair("Подтвердить сброс",()->send("rule_reset",q->q.addProperty("confirmed",true)),"Отмена",()->{confirm=false;clearAndInit();});pair("Удалить правило и его связи",()->send("rule_delete",q->q.addProperty("confirmed",true)),"Отмена",()->{confirm=false;clearAndInit();});}else row("Сброс / удаление: показать подтверждение",()->{confirm=true;clearAndInit();});row("Завершить выбор (сохранённые связи остаются)",()->send("cancel_selection",q->{}));
    }
    private void lampsTab(){JsonObject lamps=object(view,"lamps"),node=object(lamps,"node");line("1. Исходный фонарь → 2. Назначения → 3. Завершить");line("Источник: "+string(node,"name","не выбран"));mode(BuildingTool.Action.LAMP_SOURCE,bool(view,"operator"),"Настройка сети доступна оператору уровня 2.");
        line("Имя выбранного фонаря");field(draftLampName,64,v->draftLampName=v);row("Применить имя выбранного фонаря",()->lamp("RENAME",null,null,false));
        line("Именованная линия (явные связи)");field(draftLine,64,v->draftLine=v);for(JsonElement e:array(lamps,"lines")){JsonObject line=e.getAsJsonObject();row("Линия: "+string(line,"name","")+" · связей "+string(line,"connectionCount","0"),()->{draftLine=string(line,"name","");clearAndInit();});}
        pair("Создать линию",()->lamp("CREATE_LINE",null,null,false),"Переименовать → поле имени",()->lamp("RENAME_LINE",null,null,false));row("Направление: "+(draftBoth?"В обе стороны":"Только к назначению"),()->{draftBoth=!draftBoth;clearAndInit();});
        row("Применить параметры назначения",()->send("lamp_parameters",q->{q.addProperty("line",draftLine);q.addProperty("both",draftBoth);}));mode(BuildingTool.Action.LAMP_TARGET,bool(view,"operator"),"Нужны права оператора и исходный фонарь.");line("ЛКМ добавляет назначения, источник сохраняется.");
        line("Маршруты: "+array(lamps,"outgoingNames").toString());for(JsonElement e:array(lamps,"connections")){JsonObject c=e.getAsJsonObject(),a=object(c,"source"),b=object(c,"destination");String current=string(node,"entityUuid","");JsonObject dest=current.equals(string(a,"entityUuid",""))?b:a;String source=current;String target=string(dest,"entityUuid","");line(string(c,"lineName","")+": "+string(a,"name","")+(bool(c,"aToB")&&bool(c,"bToA")?" ↔ ":bool(c,"aToB")?" → ":" ← ")+string(b,"name","")+(bool(c,"reverseOtherLines")?" · обратный путь есть в другой линии":""));pair("Направление → "+string(dest,"name","назначение"),()->{draftLine=string(c,"lineName","");lamp("SET_DIRECTION",source,target,false);},"Разорвать → "+string(dest,"name","назначение"),()->{draftLine=string(c,"lineName","");lamp("UNLINK",source,target,false);});}
        int routePage=Integer.parseInt(string(lamps,"page","0")),routePages=Integer.parseInt(string(lamps,"pageCount","1"));if(routePages>1){line("Маршруты: страница "+(routePage+1)+" / "+routePages);pair("Предыдущие маршруты",()->send("lamp_page",q->q.addProperty("page",Math.max(0,routePage-1))),"Следующие маршруты",()->send("lamp_page",q->q.addProperty("page",Math.min(routePages-1,routePage+1))));}
        if(confirm)pair("Удалить линию «"+draftLine+"»",()->lamp("DELETE_LINE",null,null,true),"Отмена",()->{confirm=false;clearAndInit();});else row("Удалить всю линию…",()->{confirm=true;clearAndInit();});row("Отменить выбор источника",()->send("cancel_selection",q->{}));
    }
    private void lamp(String action,String source,String destination,boolean confirmed){send("lamp",q->{q.addProperty("action",action);q.addProperty("line",draftLine);q.addProperty("name",draftLampName);q.addProperty("both",draftBoth);q.addProperty("confirmed",confirmed);if(source!=null)q.addProperty("source",source);if(destination!=null)q.addProperty("destination",destination);});}
    private void eventsTab(){if(!bool(view,"admin")){disabled("Редактор команд","Требуются серверные права администратора уровня 4; Creative их не заменяет.");return;}if(!bool(target(),"openable")){disabled("После открытия / закрытия","Выберите объект с настоящими устойчивыми состояниями. Для импульсного или статичного типа эти события отсутствуют.");return;}
        row(commandOpen?"После открытия":"После закрытия",()->{commandOpen=!commandOpen;loadCommands();clearAndInit();});line("Команды сервера по порядку; сохраняются только кнопкой ниже.");for(int i=0;i<commandDraft.size();i++){final int index=i;row((i+1)+". "+commandDraft.get(i),()->{commandIndex=index;draftCommand=commandDraft.get(index);clearAndInit();});}
        field(draftCommand,2048,v->draftCommand=v);pair(commandIndex<0?"Добавить команду":"Изменить выбранную",()->{if(!draftCommand.isBlank()){if(commandIndex<0&&commandDraft.size()<32)commandDraft.add(draftCommand);else if(commandIndex>=0)commandDraft.set(commandIndex,draftCommand);draftCommand="";commandIndex=-1;clearAndInit();}},"Убрать выбранную",()->{if(commandIndex>=0){commandDraft.remove(commandIndex);commandIndex=-1;draftCommand="";clearAndInit();}});
        pair("Переместить выше",()->moveCommand(-1),"Переместить ниже",()->moveCommand(1));pair("Сохранить список команд",()->send("commands",q->{q.addProperty("open",commandOpen);JsonArray a=new JsonArray();commandDraft.forEach(a::add);q.add("commands",a);}),"Отмена формы",()->{loadCommands();clearAndInit();});
        line("Подстановки: {id}, {uuid}, {x}, {y}, {z}, {dimension}, {player}");line("Без игрока команда с {player} пропускается. UUID блока не является @e.");line("Пример: execute positioned {x} {y} {z} run playsound minecraft:block.note_block.bell master @a[distance=..16]");
    }
    private void moveCommand(int delta){int next=commandIndex+delta;if(commandIndex>=0&&next>=0&&next<commandDraft.size()){Collections.swap(commandDraft,commandIndex,next);commandIndex=next;clearAndInit();}}
    private void diagnosticsTab(){line("Осмотр и снимок не меняют объект.");mode(BuildingTool.Action.SELECT,true,"");mode(BuildingTool.Action.DIAGNOSTICS,bool(view,"operator"),"Снимки доступны оператору уровня 2.");line("Пометка к снимку / записи");field(draftNote,512,v->draftNote=v);row("Сохранить снимок выбранного объекта",()->diagnostics("snapshot",true));pair("Запись 60 с: всё",()->diagnostics("start",false),"60 с: выбранный объект",()->diagnostics("start",true));pair("Остановить запись",()->diagnostics("stop",false),"Сохранить пометку",()->diagnostics("mark",false));pair("Обновить статус",()->diagnostics("status",false),"Экспорт ZIP",()->diagnostics("export",false));JsonObject d=object(view,"diagnostics");line(bool(d,"enabled")?"Идёт запись · осталось "+string(d,"remainingSeconds","?")+" с":"Запись выключена · "+string(d,"stopReason",""));line("Сеанс: "+string(d,"sessionId","NONE"));line("FPS ≠ точная нагрузка блока; CPU рендера ≠ время GPU.");if(details)for(var entry:d.entrySet())line(entry.getKey()+": "+entry.getValue());}
    private void diagnostics(String action,boolean selected){send("diagnostics",q->{q.addProperty("action",action);q.addProperty("note",draftNote);q.addProperty("selected",selected);});}
    private void rightInfo(){JsonObject t=target();rightLines.add("Параметры и выбранный экземпляр");rightLines.add(string(t,"name","Нет объекта под прицелом"));rightLines.add(string(t,"kind","")+" ["+string(t,"id","?????")+"]");rightLines.add("Положение: "+string(t,"position","—"));rightLines.add("Смещение Y: "+string(t,"offset","—"));rightLines.add(bool(view,"pinned")?"Закреплённый выбор":"Объект под прицелом");rightLines.add("Один ЛКМ — одна операция.");rightLines.add("ПКМ открывает меню.");rightLines.add("Разрушение с инструментом отменено.");JsonObject r=rule();if(r.size()>0){rightLines.add("Правило: "+string(r,"name",""));rightLines.add("Активированы "+string(r,"active","0")+" из "+string(r,"total","0"));}if(details){rightLines.add("Registry: "+string(t,"registry","—"));rightLines.add("UUID: "+string(t,"instance","—"));rightLines.add("Измерение: "+string(t,"dimension","—"));} }
    @Override public void render(DrawContext c,int mx,int my,float delta){renderBackground(c);c.fill(4,4,width-4,height-4,0xE018181D);c.drawCenteredTextWithShadow(textRenderer,title,width/2,10,0xDEC395);c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth("Действие: "+string(view,"actionLabel","выбрать"),width-20)),10,27,0xE2D5B6);JsonObject t=target();c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth((bool(view,"pinned")?"Закреплён: ":"Прицел: ")+label(t),width-20)),10,41,0xC5C5C5);c.drawTextWithShadow(textRenderer,Text.literal(textRenderer.trimToWidth(string(view,"message",""),width-20)),10,57,0xE1B272);
        if(width>=650){c.fill(right-5,75,right-4,bodyBottom,0xFF504736);int y=82;for(String line:rightLines)for(var part:textRenderer.wrapLines(Text.literal(line),Math.max(100,width-right-12))){if(y>=bodyBottom-10)break;c.drawTextWithShadow(textRenderer,part,right+2,y,0xD6C8AF);y+=12;} }
        c.drawCenteredTextWithShadow(textRenderer,Text.literal("Страница "+(page+1)+" / "+Math.max(1,(rows.size()+rowsPerPage-1)/rowsPerPage)+" · прокрутка колесом · Esc без применения формы"),central+columnWidth/2,height-16,0xA4A4A4);super.render(c,mx,my,delta);}
    @Override public boolean mouseScrolled(double x,double y,double amount){if(amount!=0){int next=Math.max(0,Math.min(Math.max(0,(rows.size()-1)/rowsPerPage),page+(amount<0?1:-1)));if(next!=page){page=next;clearAndInit();}return true;}return super.mouseScrolled(x,y,amount);}
    private static JsonObject object(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonObject()?o.getAsJsonObject(k):new JsonObject();}
    private static JsonArray array(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonArray()?o.getAsJsonArray(k):new JsonArray();}
    private static String string(JsonObject o,String k,String fallback){return o.has(k)&&o.get(k).isJsonPrimitive()?o.get(k).getAsString():fallback;}
    private static boolean bool(JsonObject o,String k){return o.has(k)&&o.get(k).isJsonPrimitive()&&o.get(k).getAsBoolean();}
    private static String label(JsonObject o){return o.size()==0?"Нет выбранного объекта":string(o,"name","")+" ["+string(o,"id","?????")+"] · "+string(o,"position","");}
    private static String mountName(String mount){return switch(mount){case "FLOOR"->"Пол";case "CEILING"->"Потолок";default->"Вертикально";};}
    private static String condition(String value){return value.equals("ALL")?"Все":"Любой";}
    private static String effect(String value){return switch(value){case "OPEN"->"Только открывать";case "CLOSE"->"Только закрывать";case "PULSE"->"Одиночная анимация";default->"Открывать и закрывать";};}
}
