package dev.dreamwalker.bloodbornedw.review;

import com.google.gson.*;
import com.mojang.authlib.GameProfile;
import dev.dreamwalker.bloodbornedw.debug.DebugCatalogue;
import dev.dreamwalker.bloodbornedw.link.MechanismLinks;
import dev.dreamwalker.bloodbornerp.content.SourceLegacyPayload;
import dev.dreamwalker.bloodbornerp.object.*;
import java.nio.file.*;
import java.util.*;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.event.lifecycle.v1.*;
import net.minecraft.block.*;
import net.minecraft.entity.*;
import net.minecraft.item.*;
import net.minecraft.nbt.*;
import net.minecraft.network.*;
import net.minecraft.network.packet.Packet;
import net.minecraft.registry.Registries;
import net.minecraft.server.*;
import net.minecraft.server.network.*;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.*;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.*;
import net.minecraft.world.*;
import net.minecraft.world.gen.chunk.FlatChunkGenerator;

/** Optional separate disk compatibility probe; never part of the production JAR. */
public final class ReviewV10AliasCompatibilityBootstrap implements ModInitializer {
    private static final String INPUT="review-v10-alias-input.json",OUTPUT="review-v10-alias-output.json",STATE="dw_review_v10_alias_fixture";
    private static final List<String> FIELDS=List.of("id","UUID","Pos","Rotation","Open","Locked","Scale","VerticalOffset","CustomName","Links",SourceLegacyPayload.KEY,"OpaqueAliasProbe");
    private static final Map<MinecraftServer,Run> RUNS=new WeakHashMap<>();
    @Override public void onInitialize(){
        ServerLifecycleEvents.SERVER_STARTED.register(server->{if(!Files.isRegularFile(Path.of(INPUT)))return;try{RUNS.put(server,new Run(server));}catch(Throwable failure){fail(null,failure);}});
        ServerTickEvents.END_SERVER_TICK.register(server->{Run run=RUNS.get(server);if(run==null)return;try{run.tick();}catch(Throwable failure){run.restore();fail(run,failure);RUNS.remove(server);}});
        ServerLifecycleEvents.SERVER_STOPPED.register(server->{Run run=RUNS.remove(server);if(run!=null){run.restore();fail(run,new IllegalStateException("Server stopped before bounded compatibility proof completed"));}});
    }
    private static final class Saved extends PersistentState {
        NbtList rows=new NbtList(),items=new NbtList();String artifact="";
        static Saved read(NbtCompound n){require(n.getInt("Schema")==2,"Exact alias journal schema2 with saved old inventory required");Saved s=new Saved();s.rows=n.getList("Rows",NbtElement.COMPOUND_TYPE).copy();s.items=n.getList("Items",NbtElement.COMPOUND_TYPE).copy();s.artifact=n.getString("Artifact");return s;}
        @Override public NbtCompound writeNbt(NbtCompound n){n.putInt("Schema",2);n.putString("Artifact",artifact);n.put("Rows",rows.copy());n.put("Items",items.copy());return n;}
    }
    private static final class Run {
        final MinecraftServer server;final ServerWorld world;final JsonObject marker,report=new JsonObject();final JsonArray fixtures=new JsonArray(),probes=new JsonArray();
        final Map<Long,Boolean> forced=new LinkedHashMap<>();final List<RpObjectEntity> authored=new ArrayList<>();final List<String> aliases=new ArrayList<>();final ServerPlayerEntity actor;final String mode;final Saved saved;
        int age,step,pair,waiting;RpObjectEntity pendingOld,pendingNew;ItemStack pendingStack;NbtCompound pendingStackNbt;Set<UUID> before=new HashSet<>();JsonObject probe;String originalFourteen="";
        Run(MinecraftServer server)throws Exception{
            this.server=server;world=server.getOverworld();require(Files.size(Path.of(INPUT))<=16384,"Bounded marker required");marker=JsonParser.parseString(Files.readString(Path.of(INPUT))).getAsJsonObject();mode=marker.get("mode").getAsString();
            require(marker.get("schema").getAsString().equals("dw-v10-alias-disk-input-v1")&&marker.get("revision").getAsString().equals("V10")&&marker.get("guard").getAsString().equals("QA_ONLY_FRESH_ALIAS_AUTHOR_OR_DISTINCT_SAVED_REENTER"),"Exact separate alias marker guard required");
            require(Set.of("AUTHOR","REENTER").contains(mode)&&server.getSaveProperties().getLevelName().equals("isolated-smoke-world")&&world.getChunkManager().getChunkGenerator() instanceof FlatChunkGenerator&&!Files.exists(Path.of(OUTPUT)),"Wrong mode/world/generator or prior output");
            report.addProperty("schema","dw-v10-alias-disk-output-v1");report.addProperty("mode",mode);report.addProperty("status","RUNNING");report.addProperty("markerSha256",ReviewV10ProofSupport.sha(Files.readAllBytes(Path.of(INPUT))));ReviewV10ProofSupport.artifact(marker,report);
            report.addProperty("manualClientRenderOrPacketProof","NOT_RUN_SERVER_TECHNICAL_DISK_AND_REAL_ITEM_DAMAGE_APIS_ONLY");report.addProperty("linkHookScope","Furniture aliases are static unsupported mechanism targets; preserved raw Links and typed opaque provenance, no fabricated active route/hook function");report.add("fixtures",fixtures);report.add("probes",probes);
            aliases.addAll(RpObjectCompatibility.ALIASES.keySet());Collections.sort(aliases);require(aliases.size()==7,"Frozen7 alias pairs required");
            actor=new ServerPlayerEntity(server,world,new GameProfile(UUID.randomUUID(),"AliasDiskQA")){@Override public boolean hasPermissionLevel(int level){return level<=4;}};
            actor.networkHandler=new ServerPlayNetworkHandler(server,new ClientConnection(NetworkSide.SERVERBOUND){@Override public void send(Packet<?> p){}@Override public void send(Packet<?> p,PacketCallbacks c){}},actor);actor.changeGameMode(GameMode.CREATIVE);actor.getAbilities().allowModifyWorld=true;
            boolean exists=world.getPersistentStateManager().get(Saved::read,STATE)!=null;require(mode.equals("AUTHOR")?!exists:exists,"AUTHOR requires fresh state; REENTER requires actual saved state");saved=world.getPersistentStateManager().getOrCreate(Saved::read,Saved::new,STATE);
            if(mode.equals("REENTER"))require(saved.artifact.equals(marker.get("productionJarSha256").getAsString())&&saved.rows.size()==14&&saved.items.size()==7,"Saved artifact/14instance/7inventory evidence differs");
            try{for(int x=-4;x<=1;x++)for(int z=0;z<=4;z++){ChunkPos c=new ChunkPos(x,z);forced.put(c.toLong(),world.getForcedChunks().contains(c.toLong()));world.setChunkForced(x,z,true);world.getChunk(x,z);}}catch(RuntimeException|Error failure){restore();throw failure;}
            report.addProperty("temporaryChunkForcingScope","30 declared chunks only; previous flags restored before final save; actual process stop/reenter verified by launcher and independent saved-world reader");
        }
        void tick()throws Exception{
            age++;require(age<=600,"Bounded600 server tick proof exceeded");if(age<30)return;
            if(step==0){if(mode.equals("AUTHOR")){author();step=1;}else{if(!allSavedLoaded())return;verifyFourteen();verifyInventory();originalFourteen=digestFourteen();step=2;}return;}
            if(step==1){if(authored.stream().anyMatch(e->world.getEntity(e.getUuid())!=e))return;require(saved.rows.isEmpty()&&saved.items.isEmpty(),"No prior fixture rows/items");for(RpObjectEntity e:authored)saved.rows.add(row(e));authorInventory();saved.artifact=marker.get("productionJarSha256").getAsString();saved.markDirty();verifyFourteen();verifyInventory();require(server.save(false,true,true),"Actual AUTHOR disk save failed");report.addProperty("actualSave",true);report.addProperty("status","PASS_ALIAS_AUTHOR_14_INSTANCES_REQUIRES_DISTINCT_DISK_REENTER");finish();return;}
            if(step==2){if(pair==aliases.size()){require(originalFourteen.equals(digestFourteen()),"Temporary ordinary probes changed one of14persisted instances");report.addProperty("permanentFourteenBeforeSha256",originalFourteen);report.addProperty("permanentFourteenAfterSha256",digestFourteen());require(server.save(false,true,true),"Actual REENTER disk save failed");report.addProperty("actualSave",true);report.addProperty("status","PASS_ALIAS_DISTINCT_DISK_REENTER_14_PRESERVED_AND_7_CANONICAL_OLD_ITEM_PROBES");finish();return;}beginProbe();step=3;waiting=0;return;}
            if(step==3){waiting++;require(waiting<=100,"Accepted old item spawn was not tracked within100ticks");List<RpObjectEntity> added=near(probeRoot(48)).stream().filter(e->!before.contains(e.getUuid())&&e.assetId().equals(RpObjectCompatibility.canonicalId(aliases.get(pair)))).toList();if(added.isEmpty()||world.getEntity(pendingOld.getUuid())!=pendingOld)return;require(added.size()==1,"One old item operation created another count");pendingNew=added.get(0);verifyNew();attack(pendingOld,"oldRegistryTemporaryProbe");step=4;return;}
            if(step==4){require(pendingOld.isRemoved()&&world.getEntity(pendingOld.getUuid())==null,"Old registry ordinary Creative attack did not remove exactly one instance");require(drops().isEmpty(),"Old registry attack fabricated an item drop");attack(pendingNew,"newCanonicalTemporaryProbe");step=5;return;}
            if(step==5){require(pendingNew.isRemoved()&&world.getEntity(pendingNew.getUuid())==null,"Canonical ordinary Creative attack did not remove instance");require(drops().isEmpty(),"Canonical attack fabricated an item drop");require(originalFourteen.equals(digestFourteen()),"Attack changed a persisted same-type instance");probe.addProperty("oldAndCanonicalCreativeDrops",0);probe.addProperty("exactTwoTemporaryInstancesRemoved",true);probe.addProperty("permanentFourteenUnchanged",true);probe.addProperty("status","PASS_SERVER_OLD_ITEM_CANONICAL_PICK_FRESH_UUID_TYPED_SETTINGS_AND_RAY_VALIDATED_CREATIVE_ATTACK");probes.add(probe);pair++;step=2;}
        }
        void author(){
            for(int i=0;i<aliases.size();i++)for(int n=0;n<2;n++){
                String alias=aliases.get(i);BlockPos root=new BlockPos(-42+i*7,64,16+n*8);foundation(root);RpObjectEntity e=ObjectRegistry.TYPES.get(alias).create(world);require(e!=null,"Alias factory unavailable");e.refreshPositionAndAngles(root.getX()+.375,64+.125+n*.375,root.getZ()+.875,45*i+n*90,0);
                NbtCompound source=e.writeNbt(new NbtCompound());source.putString("id","bloodborne_rp:"+alias);source.putBoolean("Open",n==1);source.putBoolean("Locked",n==0);source.putFloat("Scale",1+n*.25f);source.putDouble("VerticalOffset",.125+n*.375);source.putString("CustomName",Text.Serializer.toJson(Text.literal("same type distinct saved "+alias+" instance "+n)));
                NbtList links=new NbtList();links.add(NbtHelper.fromUuid(UUID.randomUUID()));source.put("Links",links);source.putInt("AnimationId",0);NbtCompound opaque=new NbtCompound();opaque.putString("Role","preserved_source_opaque_not_an_active_hook");opaque.putInt("InstanceIndex",n);opaque.putByteArray("TypedBytes",new byte[]{0,1,-1,(byte)i});source.put("OpaqueAliasProbe",opaque);e.readNbt(source.copy());require(e.getUuid().equals(source.getUuid("UUID")),"Existing UUID changed on typed source read");require(world.spawnEntity(e),"Exact old registry fixture spawn refused");authored.add(e);
            }
        }
        boolean allSavedLoaded(){for(NbtElement raw:saved.rows)if(world.getEntity(((NbtCompound)raw).getUuid("UUID"))==null)return false;return true;}
        void authorInventory(){for(int i=0;i<aliases.size();i++){String alias=aliases.get(i);ItemStack stack=Registries.ITEM.get(new Identifier("bloodborne_rp",alias+"_placer")).getDefaultStack();stack.setCustomName(Text.literal("saved old inventory constructor "+alias));NbtCompound itemState=new NbtCompound();itemState.putBoolean("Open",(i&1)==1);itemState.putBoolean("Locked",(i&1)==0);itemState.putFloat("Scale",.875f+i*.0625f);stack.getOrCreateNbt().put("bloodborne_rp_object",itemState);RpObjectEntity holder=authored.get(i*2);stack.getOrCreateNbt().putUuid("UUID",holder.getUuid());stack.getOrCreateNbt().put("Links",holder.writeNbt(new NbtCompound()).getList("Links",NbtElement.INT_ARRAY_TYPE).copy());NbtCompound opaque=new NbtCompound();opaque.putByteArray("TypedBytes",new byte[]{0,1,-1,(byte)i});opaque.putString("Scope","old inventory metadata preserved on held stack, not a new entity identity");stack.getOrCreateNbt().put("AliasInventoryOpaque",opaque);NbtCompound item=new NbtCompound();item.putString("Alias",alias);item.put("Stack",stack.writeNbt(new NbtCompound()));saved.items.add(item);}}
        void verifyInventory()throws Exception{require(saved.items.size()==7,"Seven exact old inventory stacks required");JsonArray rows=new JsonArray();Set<String> found=new HashSet<>();for(NbtElement raw:saved.items){NbtCompound row=(NbtCompound)raw;String alias=row.getString("Alias");NbtCompound expected=row.getCompound("Stack");ItemStack stack=ItemStack.fromNbt(expected.copy());require(found.add(alias)&&aliases.contains(alias)&&Registries.ITEM.getId(stack.getItem()).toString().equals("bloodborne_rp:"+alias+"_placer")&&stack.writeNbt(new NbtCompound()).equals(expected),"Old saved inventory ItemStack.fromNbt changed original registry or typed NBT");JsonObject item=new JsonObject();item.addProperty("aliasItem","bloodborne_rp:"+alias+"_placer");item.addProperty("savedTypedStackNbtBase64",Base64.getEncoder().encodeToString(bytes(expected)));item.addProperty("savedTypedStackSha256",ReviewV10ProofSupport.sha(bytes(expected)));item.addProperty("parsedAndSerializedTypedEqual",true);rows.add(item);}report.add("savedOldInventoryStacks",rows);report.addProperty("savedOldInventoryStackCount",7);}
        void verifyFourteen()throws Exception{
            Set<UUID> ids=new HashSet<>();Map<String,Integer> count=new HashMap<>();fixtures.asList().clear();
            for(NbtElement raw:saved.rows){NbtCompound expected=(NbtCompound)raw;Entity found=world.getEntity(expected.getUuid("UUID"));require(found instanceof RpObjectEntity,"Saved alias UUID absent");RpObjectEntity e=(RpObjectEntity)found;String alias=expected.getString("Alias"),canonical=RpObjectCompatibility.canonicalId(alias);
                require(ids.add(e.getUuid())&&row(e).equals(expected),"Saved full typed identity/pose/settings/provenance changed "+alias);require(Registries.ENTITY_TYPE.getId(e.getType()).getPath().equals(alias)&&e.originalRegistryAssetId().equals(alias)&&e.assetId().equals(canonical),"Raw registry/logical canonical art differs");require(e.asset().model().equals(dev.dreamwalker.bloodbornerp.content.AssetCatalog.get(canonical).model()),"Canonical selected model differs");require(DebugCatalogue.entry(Registries.ENTITY_TYPE.getId(e.getType())).equals(DebugCatalogue.entry(new Identifier("bloodborne_rp",canonical))),"Debug TEMP canonical identity differs");
                require(!e.canBeLinked()&&!e.isMechanism(),"Static furniture unexpectedly activated mechanism behavior");ItemStack picked=e.getPickBlockStack();require(Registries.ITEM.getId(picked.getItem()).getPath().equals(canonical+"_placer")&&picked.getName().equals(e.getCustomName())&&picked.getSubNbt("bloodborne_rp_object").getBoolean("Locked")==e.isLocked()&&picked.getSubNbt("bloodborne_rp_object").getFloat("Scale")==e.objectScale(),"Canonical pick lost held settings/name");require(!picked.getNbt().contains("UUID")&&!picked.getNbt().contains("Links")&&!picked.getSubNbt("bloodborne_rp_object").contains("VerticalOffset"),"Pick cloned instance-owned identity/links/height");
                require(aimAt(e,true),"No actual debug ray to saved alias instance");int debug=server.getCommandManager().executeWithPrefix(actor.getCommandSource().withLevel(4),"bb debug");require(debug>0&&row(e).equals(expected),"Ordinary /bb debug failed or edited saved alias");
                count.merge(alias,1,Integer::sum);JsonObject result=new JsonObject();result.addProperty("alias",alias);result.addProperty("canonical",canonical);result.addProperty("uuid",e.getUuidAsString());result.addProperty("temporaryId",DebugCatalogue.entry(Registries.ENTITY_TYPE.getId(e.getType())).temporaryId());result.addProperty("expectedTypedNbtBase64",Base64.getEncoder().encodeToString(bytes(expected.getCompound("Stable"))));result.addProperty("stableTypedSha256",ReviewV10ProofSupport.sha(bytes(stable(e))));result.addProperty("currentAndExpectedTypedEqual",true);result.addProperty("policyLookupKey",MechanismLinks.TargetRef.rp(e).key());result.addProperty("linksHooksFunction","UNSUPPORTED_STATIC_TYPE; rawLinks/provenance preserved, no routes invented");result.addProperty("actualDebugCommand","bb debug");result.addProperty("actualDebugResult",debug);result.addProperty("exactCommandEntityRay",true);result.addProperty("canonicalModelSelected",e.asset().model().toString());fixtures.add(result);
            }require(ids.size()==14&&count.size()==7&&count.values().stream().allMatch(n->n==2),"Two map instances per old alias must survive without deduplication");report.addProperty("persistedOldInstanceCount",14);report.addProperty("persistedOldAliasTypeCount",7);
        }
        void beginProbe(){
            String alias=aliases.get(pair);String canonical=RpObjectCompatibility.canonicalId(alias);BlockPos root=probeRoot(48);foundation(root);foundation(probeRoot(60));before.clear();for(RpObjectEntity e:near(root))before.add(e.getUuid());require(drops().isEmpty(),"Temporary drop area already occupied");
            NbtCompound savedItem=saved.items.getCompound(pair);require(savedItem.getString("Alias").equals(alias),"Saved old item order differs");NbtCompound originalStack=savedItem.getCompound("Stack");pendingStack=ItemStack.fromNbt(originalStack.copy());require(Registries.ITEM.getId(pendingStack.getItem()).toString().equals("bloodborne_rp:"+alias+"_placer")&&pendingStack.writeNbt(new NbtCompound()).equals(originalStack),"Actual disk old ItemStack did not parse exactly");pendingStackNbt=pendingStack.getNbt().copy();actor.setPosition(root.getX()+.5,64,root.getZ()-3.5);actor.setYaw(0);actor.setPitch(22);actor.setStackInHand(Hand.MAIN_HAND,pendingStack);actor.setStackInHand(Hand.OFF_HAND,ItemStack.EMPTY);
            ActionResult result=pendingStack.useOnBlock(new ItemUsageContext(actor,Hand.MAIN_HAND,new BlockHitResult(new Vec3d(root.getX()+.5,64,root.getZ()+.5),Direction.UP,root.down(),false)));require(result.isAccepted(),"Actual old alias Item.useOnBlock refused");require(pendingStack.getCount()==1&&pendingStack.getNbt().equals(pendingStackNbt),"Creative held item typed NBT changed/consumed");
            pendingOld=ObjectRegistry.TYPES.get(alias).create(world);require(pendingOld!=null,"Temporary old alias factory absent");pendingOld.refreshPositionAndAngles(probeRoot(60).getX(),64,60,0,0);pendingOld.setCustomName(Text.literal("temporary old-registry Creative guard probe"));require(world.spawnEntity(pendingOld),"Temporary old registry probe refused");
            probe=new JsonObject();probe.addProperty("aliasItem","bloodborne_rp:"+alias+"_placer");probe.addProperty("canonical",canonical);probe.addProperty("itemResult",result.toString());probe.addProperty("itemPath","actual saved old ItemStack.fromNbt -> real server ItemStack.useOnBlock/ItemUsageContext; NOT a client packet or direct ObjectRegistry.place call");probe.addProperty("oldInventoryDiskRoundtrip",true);probe.addProperty("heldTypedNbtPreserved",pendingStack.writeNbt(new NbtCompound()).equals(originalStack));probe.addProperty("oldAttackProbeScope","temporary exact old EntityType, not a deleted/recreated member of the14disk fixtures");
        }
        void verifyNew(){
            String canonical=RpObjectCompatibility.canonicalId(aliases.get(pair));NbtCompound expectedState=pendingStackNbt.getCompound("bloodborne_rp_object");require(Registries.ENTITY_TYPE.getId(pendingNew.getType()).getPath().equals(canonical)&&saved.rows.stream().noneMatch(n->((NbtCompound)n).getUuid("UUID").equals(pendingNew.getUuid()))&&!pendingNew.getUuid().equals(pendingStackNbt.getUuid("UUID")),"Old item failed canonical new registry/UUID contract");require(pendingNew.hasCustomName()&&pendingNew.getCustomName().equals(pendingStack.getName())&&pendingNew.isOpen()==expectedState.getBoolean("Open")&&pendingNew.isLocked()==expectedState.getBoolean("Locked")&&pendingNew.objectScale()==expectedState.getFloat("Scale")&&pendingNew.verticalOffset()==0&&pendingNew.links().isEmpty(),"New canonical instance copied another setting/identity/link");ItemStack picked=pendingNew.getPickBlockStack();require(Registries.ITEM.getId(picked.getItem()).getPath().equals(canonical+"_placer")&&picked.getName().equals(pendingStack.getName())&&picked.getSubNbt("bloodborne_rp_object").equals(expectedState)&&!picked.getNbt().contains("UUID")&&!picked.getNbt().contains("Links")&&!picked.getNbt().contains("AliasInventoryOpaque"),"Picked canonical state differs from held alias state or copied old inventory identity");probe.addProperty("newUuid",pendingNew.getUuidAsString());probe.addProperty("newRegistry",Registries.ENTITY_TYPE.getId(pendingNew.getType()).toString());probe.addProperty("pickCanonical",true);probe.addProperty("newLinksEmpty",true);probe.addProperty("oldInventoryIdentityNotCopied",true);
        }
        void attack(RpObjectEntity e,String role){
            actor.setStackInHand(Hand.MAIN_HAND,ItemStack.EMPTY);actor.setStackInHand(Hand.OFF_HAND,ItemStack.EMPTY);
            require(aimAt(e,false),"No real selected part ray to temporary Creative attack target");require(e.damage(world.getDamageSources().playerAttack(actor),1),"Actual creative DamageSource/ray guard refused");probe.addProperty(role+"Uuid",e.getUuidAsString());probe.addProperty(role+"ActualRayAndDamageGuard",true);
        }
        boolean aimAt(RpObjectEntity e,boolean debug){for(Box b:e.selectionBoxes()){Vec3d point=b.getCenter();for(Vec3d delta:List.of(new Vec3d(0,0,-2),new Vec3d(0,0,2),new Vec3d(-2,0,0),new Vec3d(2,0,0))){Vec3d eye=point.add(delta);actor.setPosition(eye.x,eye.y-actor.getStandingEyeHeight(),eye.z);aim(actor,point);if(debug){var hit=actor.raycast(6,0,false);double limit=hit.getType()==net.minecraft.util.hit.HitResult.Type.BLOCK?hit.getPos().squaredDistanceTo(actor.getEyePos()):36;if(dev.dreamwalker.bloodbornedw.debug.CatalogueDebug.entityTarget(actor,limit)==e)return true;}else{var selected=RpObjectSelection.playerTarget(actor,6);if(selected!=null&&selected.getEntity()==e)return true;}}}return false;}
        BlockPos probeRoot(int z){return new BlockPos(-42+pair*7,64,z);}
        List<RpObjectEntity> near(BlockPos root){return world.getEntitiesByClass(RpObjectEntity.class,new Box(root).expand(6),e->!e.isRemoved());}
        List<ItemEntity> drops(){return world.getEntitiesByClass(ItemEntity.class,new Box(-52,55,36,16,90,72),e->!e.isRemoved());}
        void foundation(BlockPos root){for(int x=-2;x<=2;x++)for(int z=-2;z<=2;z++){BlockPos p=root.add(x,-1,z);require(world.getBlockEntity(p)==null,"Fixture foundation would replace BE");require(world.getBlockState(p).isAir()||world.getBlockState(p).isOf(Blocks.GRASS_BLOCK)||world.getBlockState(p).isOf(Blocks.DIRT)||world.getBlockState(p).isOf(Blocks.STONE),"Fixture foundation contains foreign state");world.setBlockState(p,Blocks.STONE.getDefaultState(),Block.NOTIFY_ALL);}}
        String digestFourteen()throws Exception{NbtList rows=new NbtList();for(NbtElement raw:saved.rows){Entity e=world.getEntity(((NbtCompound)raw).getUuid("UUID"));require(e instanceof RpObjectEntity,"Persisted same-type instance absent");rows.add(row((RpObjectEntity)e));}NbtCompound all=new NbtCompound();all.put("Rows",rows);return ReviewV10ProofSupport.sha(bytes(all));}
        void restore(){for(var entry:forced.entrySet()){ChunkPos p=new ChunkPos(entry.getKey());world.setChunkForced(p.x,p.z,entry.getValue());}actor.discard();}
        void finish()throws Exception{restore();require(server.save(false,true,true),"Final save with restored forced flags failed");report.addProperty("forcedChunksTouched",forced.size());report.addProperty("forcedFlagsRestored",forced.entrySet().stream().allMatch(e->world.getForcedChunks().contains(e.getKey())==e.getValue()));report.addProperty("actualFinalSave",true);write(report);RUNS.remove(server);}
    }
    private static NbtCompound stable(RpObjectEntity e){NbtCompound raw=e.writeNbt(new NbtCompound()),out=new NbtCompound();raw.putString("id",Registries.ENTITY_TYPE.getId(e.getType()).toString());for(String key:FIELDS)if(raw.contains(key))out.put(key,raw.get(key).copy());return out;}
    private static NbtCompound row(RpObjectEntity e){NbtCompound row=new NbtCompound();row.putString("Alias",e.originalRegistryAssetId());row.putUuid("UUID",e.getUuid());row.put("Stable",stable(e));return row;}
    private static byte[] bytes(NbtCompound n){return dev.dreamwalker.bloodbornedw.composite.CompositeData.bytes(n);}
    private static void aim(ServerPlayerEntity p,Vec3d point){Vec3d d=point.subtract(p.getEyePos());p.setYaw((float)Math.toDegrees(Math.atan2(-d.x,d.z)));p.setHeadYaw(p.getYaw());p.setPitch((float)-Math.toDegrees(Math.atan2(d.y,Math.hypot(d.x,d.z))));}
    private static void require(boolean ok,String reason){if(!ok)throw new IllegalStateException(reason);}
    private static void fail(Run run,Throwable failure){JsonObject out=run==null?new JsonObject():run.report;out.addProperty("schema","dw-v10-alias-disk-output-v1");out.addProperty("status","FAIL_ALIAS_ACTUAL_DISK_COMPATIBILITY");out.addProperty("failure",failure.toString());out.addProperty("manualClientAcceptance","NOT_RUN");write(out);}
    private static void write(JsonObject out){try{Files.writeString(Path.of(OUTPUT),new GsonBuilder().setPrettyPrinting().create().toJson(out));}catch(Exception failure){throw new IllegalStateException("Unable to write alias proof",failure);}}
}
